### ISSUE TITLE
List of TODOs before first release

### ISSUE THREAD

**Issue by hcho3** [dmlc/treelite#1]
Items with strikethroughs are finished

**To-do's by first release**
* ~~Implement shared library generation scripts in Python: need at least gcc, MSVC, clang~~
* ~~Separate out runtime library (`libtreelite_runtime.so`) from the rest of tree-lite (`libtreelite.so`)~~
* ~~Finalize Python API and subpackage organization~~
* ~~Add a library of prediction transform functions that transform margins into probabilities. Each library will have `predict_margin` and `pred_transform` functions~~
* Write a polished IPython notebooks to go through steps of importing scikit-learn models.
  - will need to elaborate on idiosyncrasies, e.g. how to encode random forest classifiers with multiple classes.
* ~~Submit to PyPI~~

**Postponed items**
* Offer R binding
* Add integration and unit tests
* Hook up Continuous Integration service
* Add ranking facilities to `DMatrix` class
* Support "base predictor": a set of base margins before the first trees
* Support weighted instances (e.g. for Adaboost)

**Comment by yupbank** [comment]
this might be interesting for you ?
i can make the template for xgboost actually 

https://github.com/nok/sklearn-porter/blob/master/sklearn_porter/classifier/RandomForestClassifier/__init__.py

**Comment by hcho3** [comment]
@yupbank This is interesting indeed. Thanks for the link.

One issue with XGBoost is that XGBoost models don't expose their internal representations on Python side. So you'd need to write C code to interact with XGBoost.

**Comment by hcho3** [comment]
@yupbank In fact, the link is quite relevant in that someone already suggested a [Javascript backend](https://github.com/dmlc/xgboost/issues/1454).

**Comment by headupinclouds** [comment]
Can you share any sample prediction times for the treelite compiled models vs their reference implementations?  I'm very interested in how the XGBoost Boston Housing samples from the documentation performs, for example.  I realize this may vary wildly depending on the model, parameters, and architecture, but it would be very interesting to see a few data points.  Thanks!

**Comment by terrytangyuan** [comment]
Any progress on the R package yet? @hcho3

**Comment by pommedeterresautee** [comment]
Was thinking to it recently too... 
On R you can compile C++ on fly with Rcpp, does it make sense with this package? 
In that case it would be much more easier to perform than on Python (because everything required is already managed by R devtools)

**Comment by terrytangyuan** [comment]
I was thinking about using reticulate package (https://rstudio.github.com/reticulate) to make wrappers around its Python API. This way it’s also easier to maintain. It’s based on Rcpp but the benefit is that you don’t have to rewrite all the logic in R again. We’ve had pretty successful experience with it on other packages (e.g. TensorFlow and Keras) before. What do you think?

**Comment by terrytangyuan** [comment]
I was thinking about using [reticulate](https://rstudio.github.io/reticulate/) to write R interface using its existing Python APIs. It's using Rcpp at the back but the benefit is that we don't have to rewrite a lot of the logic again which would be hard to maintain. I've had pretty successful experience using it to build Keras and TensorFlow interfaces. What do you think?

**Comment by pommedeterresautee** [comment]
The big point about reticulate is that you are forcing R users to have a working Python installation. Am I right?

**Comment by terrytangyuan** [comment]
@pommedeterresautee Yea, I think it might not worth using it then given this project is primarily based on C unlike Keras, etc.

**Comment by hcho3** [comment]
I don't have a definite time estimate yet, but an R package is definitely on my to-do list. I've been lately busy writing a workshop paper on treelite. I'm not exactly familiar with R, so it may take some time to add R support.
