### ISSUE TITLE
CoreML support

### ISSUE THREAD

**Issue by guolinke** [dmlc/treelite#10]
any plans for the CoreML support ? 
Thanks

**Comment by hcho3** [comment]
As of now, not yet. The future direction of this project is still much up in the air, as I am seeking full-time employment. Hopefully, I would be able to secure employment that would let me work on treelite on a sustainable basis.

**Comment by hcho3** [comment]
Going to close this, since CoreML has their own stack for ingesting tree models: https://apple.github.io/coremltools/generated/coremltools.models.tree_ensemble.html
