### ISSUE TITLE
Gain and Cover

### ISSUE THREAD

**Issue by Chiragasourabh** [dmlc/treelite#103]
@hcho3  How to add gain and cover parameters of Nodes of tree ?

set_numerical_test_node() method of class Node doesn't take these parameters

**Comment by hcho3** [comment]
This is an oversight. I will add it soon.

**Comment by hcho3** [comment]
[The new model builder API in the upcoming Treelite 4.0](https://treelite.readthedocs.io/en/v4/treelite-api.html#treelite.model_builder.ModelBuilder) will let you specify gain and cover by calling `gain()` and `sum_hess()`, respectively.
