### ISSUE TITLE
Error loading protobuf RF model with single tree and single leaf node

### ISSUE THREAD

**Issue by jtkucera** [dmlc/treelite#104]
I created a simple protobuf representation of a Random Forest model with a single tree containing a single leaf node.  However when I try to load it I get:

Check failed: node.leaf_vector_size() > 0 (0 vs. 0)

I am using Treelite version 0.32 on Mac OS-X.  After creating the protobuf file I loaded it in Python 3.6 using the code below.

Attaching the protobuf file as a .gz file . (It is only a few bytes)
and the code to generate it.
[model1.protobuf.gz](https://github.com/dmlc/treelite/files/3388361/model1.protobuf.gz)
[test-protobuf-rf.tar.gz](https://github.com/dmlc/treelite/files/3388365/test-protobuf-rf.tar.gz)

>>> import treelite
>>> model = treelite.Model.load('model1.protobuf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/treelite/frontend.py", line 350, in load
    ctypes.byref(handle)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/treelite/core.py", line 50, in _check_call
    raise TreeliteError(_LIB.TreeliteGetLastError())
treelite.common.util.TreeliteError: b'[19:10:44] /Users/travis/build/hcho3/treelite-wheels/treelite/src/frontend/protobuf.cc:51: Check failed: node.leaf_vector_size() > 0 (0 vs. 0) \n\nStack trace returned 1 entries:\n[bt] (0) 0   libtreelite.dylib                   0x0000000110d20b7c dmlc::StackTrace[abi:cxx11]() + 364\n\n'

**Comment by hcho3** [comment]
Closing this, as I decided against supporting Protobuf in Treelite.
