### ISSUE TITLE
support for other operators in export_as_xgboost

### ISSUE THREAD

**Issue by catenamatteo** [dmlc/treelite#106]
Hello,
I'm trying to convert RankLib ensembles to xgboost using treelite. I can programmatically build an ensemble with treelite given RankLib .xml, commit, and then export_as_xgboost. Unfortunately, RankLib's split operator is "<=". While treelite seems to support this operator, when I try to export to xgboost the library complains that only the "<" operator is allowed. One way to bypass this issue is to convert every disequality in a "<" one, but this requires to change the sign of the thresholds, of the feature values, and to flip the tree. Not very practical.

Is there any particular reason for this limitation? Can I help in some way to fix this?

**Comment by hcho3** [comment]
@catenamatteo This limitation is in XGBoost: XGBoost uses "<" exclusively. Is there a reason why you want to convert to XGBoost specifically?

**Comment by catenamatteo** [comment]
the xgboost format seems to be accepted by many other libraries, in particular shap.

**Comment by hcho3** [comment]
@catenamatteo Unfortunately, our hands are tied, you will need to convert your model to use "<" operator, if you want to export it to be used in XGBoost later. The use of "<" operator is hard-cored everywhere in the XGBoost codebase.
