### ISSUE TITLE
BUG: Unable to handle kernel paging request

### ISSUE THREAD

**Issue by kevinhzh** [dmlc/treelite#108]
I am loading around 1000 xgboost models to perform treelite prediction. The treelite version is 0.32. However, the following error will appear occasionally, causing the restart of the Linux server.

![微信图片_20190829141419](https://user-images.githubusercontent.com/51855536/63914948-53548100-ca67-11e9-8f9e-92460f64e51f.jpg)

Any advice on this situation?

**Comment by hcho3** [comment]
Can you check your memory consumption?
