### ISSUE TITLE
 Failed to load dynamic shared library

### ISSUE THREAD

**Issue by chjq201410695** [dmlc/treelite#113]
system： win 10
python version： 3.6
treelite version: 0.32

-------------
I have compiled successfully in local pc. however, it raises a error when I use the compled lightgbm model.

-----------------
here is my code:

import treelite.runtime
batch = treelite.runtime.Batch.from_npy2d(test_X_ax_reg.values)
predictor = treelite.runtime.Predictor('D:/1_Student/ChengJQ/20190914_AX_Cla_compaired.dll', verbose=True)
out_pred = predictor.predict(batch)

--------------------------------
here is error infomation:

TreeliteError                             Traceback (most recent call last)
<ipython-input-15-735dd136347d> in <module>
      1 import treelite.runtime
      2 batch = treelite.runtime.Batch.from_npy2d(test_X_ax_reg.values)
----> 3 predictor = treelite.runtime.Predictor('D:/1_Student/ChengJQ/20190914_AX_Cla_compaired.dll', verbose=True)
      4 out_pred = predictor.predict(batch)

~\AppData\Roaming\Python\Python36\site-packages\treelite\runtime\predictor.py in __init__(self, libpath, nthread, verbose, include_master_thread)
    260         ctypes.c_int(nthread if nthread is not None else -1),
    261         ctypes.c_int(1 if include_master_thread else 0),
--> 262         ctypes.byref(self.handle)))
    263     # save # of output groups
    264     num_output_group = ctypes.c_size_t()

~\AppData\Roaming\Python\Python36\site-packages\treelite\runtime\predictor.py in _check_call(ret)
     44   """
     45   if ret != 0:
---> 46     raise TreeliteError(_LIB.TreeliteGetLastError())
     47 
     48 class Batch(object):

TreeliteError: b"[17:09:39] c:\\projects\\treelite-wheels\\treelite\\src\\predictor.cc:212: Check failed: lib_handle_ != nullptr Failed to load dynamic shared library `D:\\1_Student\\ChengJQ\\20190914_AX_Cla_compaired.dll'"

-------------------------
How can I fix this issue.  thanks~

**Comment by hcho3** [comment]
The latest master should not have this issue. You can get the latest nightly build from https://dev.azure.com/hcho3/treelite/_build/results?buildId=76&view=logs&jobId=29c8664d-f40e-5510-1c33-231d09c3a59e (Click on Artifacts button and select python_win_whl).

**Comment by chjq201410695** [comment]
> The latest master should not have this issue. You can get the latest nightly build from https://dev.azure.com/hcho3/treelite/_build/results?buildId=76&view=logs&jobId=29c8664d-f40e-5510-1c33-231d09c3a59e (Click on Artifacts button and select python_win_whl).

Can I install the version from PyPI ?
