### ISSUE TITLE
Different score after compiling a lightgbm model

### ISSUE THREAD

**Issue by AlexQie** [dmlc/treelite#115]
I have a lightgbm model and I use treelite to compile a .so file, but they have different predict results:
![image](https://user-images.githubusercontent.com/7459609/65032960-c5d5c400-d976-11e9-9aeb-9e4f6ec02bcf.png)

and here is my code:
```
predictor = treelite.runtime.Predictor('./mymodel.so', verbose=True)
data = np.loadtxt('service/sample.txt')

batch = treelite.runtime.Batch.from_npy2d(data)
out_pred = predictor.predict(batch)

lgb_model = lgb.Booster(model_file=tree_file_path)
lgb_pred = lgb_model.predict(data)
print(out_pred)
print(lgb_pred)
```
and I have the following configuration:
```
>>> import treelite
>>> treelite.__version__
'0.32'
>>> import lightgbm
>>> lightgbm.__version__
'2.2.3'
>>> 
```

**Comment by hcho3** [comment]
This is probably the same issue as #98 and #95. Treelite currently uses single-precision float (`float`) to store thresholds, whereas LightGBM models require double-precision floats (`double`). I'm working to fix the issue as part of 1.0 release (dmlc/treelite#111)

**Comment by eddy-avanan** [comment]
I have same issue with XGBoost

**Comment by shashankg7** [comment]
Hi, 

I am facing the same issue. 

Did we get this issue resolved? 

Thanks

**Comment by xcTorres** [comment]
Also happened

**Comment by hcho3** [comment]
The recent refactor (#196, #198, #199, #201, #203) added an option to use float64 data type, so that LightGBM models can be faithfully represented.
