### ISSUE TITLE
cpu cores for multithreading is restricted by TreelitePredictorLoad

### ISSUE THREAD

**Issue by yingjianling** [dmlc/treelite#118]
I use TreelitePredictorLoad interface to load a .so file. I find that after this interface was called, all new threads run on only single cpu core. I have tried different num_worker_thread of TreelitePredictorLoad like -1,1,2...., and I meet the same situation. Here is my code
```
class TreelitePredictor{

public:
    TreelitePredictor(): predictor_(NULL){}

    ~TreelitePredictor(){
        if (predictor_ != NULL)
            safe_treelite(TreelitePredictorFree(predictor_));
    }
    int LoadModel(const char *fname) {
        if (predictor_ != NULL) safe_treelite(TreelitePredictorFree(predictor_));
        safe_treelite(TreelitePredictorLoad(fname, -1, &predictor_));
        return 0;
    }

    int Predict(int n, float *data, float *scores) {
        if (predictor_ == NULL) {
            std::cerr << "run loadmodel first." << std::endl;
            return -1;
        }
        DenseBatchHandle dpred;
        safe_treelite(TreeliteAssembleDenseBatch(data, -1, n, dim_, &dpred));
        std::vector<float> out_result;
        size_t out_result_size;
        safe_treelite(TreelitePredictorQueryResultSize(predictor_, dpred, 0, &out_result_size));
        if (out_result_size != n) {
            std::cerr << "wrong result size !" << std::endl;
            return -1;
        }
        out_result.resize(out_result_size);
        safe_treelite(TreelitePredictorPredictBatch(predictor_, dpred, 0, 0, 0, out_result.data(), &out_result_size));
        if (out_result_size != n) {
            std::cerr << "wrong result size !" << std::endl;
            return -1;
        }
        memcpy((char *)scores, (char *)out_result.data(), out_result_size * sizeof(float));
        safe_treelite(TreeliteDeleteDenseBatch(dpred));
        return 0;
    }

    float Test(int n, float *data, float *labels) {
        std::vector<float> pred(n, 0.);
        Predict(n, data, pred.data());
        float count = 0;
        for (int i = 0; i < n; ++i) {
            if (std::floor(pred[i] + 0.5) == labels[i])
                count++;
        }
        return count / n;
    }

protected:
    PredictorHandle predictor_;
};
```
After LoadModel method is called, I tried to use multi-threading to do some other work and  meet this problem.
By the way， I can not compile the source code of treeilte-0.32. It seems like because dmlc-core folder is empty.

**Comment by yingjianling** [comment]
I think that I have found the reason. The reason is that the SetAffinity method of ThreadPool class binds the main thread to cpu core 0, which results in other new threads generated from the main thread being  automatically bound to cpu core 0.

**Comment by hcho3** [comment]
Treelite uses a custom thread pool by default. If you'd like to embed Treelite in a multi-threaded application, you should disable thread pinnning by setting environment variable `TREELITE_BIND_THREADS` to 0.

>  I can not compile the source code of treeilte-0.32

You should use `git clone --recursive https://github.com/dmlc/treelite` to get all git submodules, including dmlc-core.
