### ISSUE TITLE
Precision of threshold/value in generated c files

### ISSUE THREAD

**Issue by andosa** [dmlc/treelite#12]
Currently, the values in the model are outputted with default precision (i.e. 6 significant digits in general). 
For example if in the saved model the threshold is 
_0.51548230441328713_, then the generated c file will have _data[1].fvalue <= 0.515482_. 
This can have a very significant impact on the model accuracy, where predictions in original model and predictions from generated c code vary drastically.

Generated files should have max available (or parameterized) precision, sth like 
oss << std::setprecision(std::numeric_limits<double>::digits10 + 2);

**Comment by hcho3** [comment]
Thanks for your report. Let me publish a fix within two or three days.

**Comment by hcho3** [comment]
I've pushed a fix. Thanks for your feedback!
