### ISSUE TITLE
Will treelite able to convert Python Xgboost model which does signal processing into working C code?

### ISSUE THREAD

**Issue by karimkhanvi** [dmlc/treelite#125]
I have created one model in python using Xgboost. 
This model has signal data in csv format. I need to perform some signal processing operation on the data. For example "to remove baseline wandering and high-frequency noise, Butterworth 3rd- order filtering was performed, with bandpass frequencies between 1 and 25 Hz". 

I have used a third party library and some scipy functions to do this. 

I am able to create the c code. But how can I avail this signal processing function in it? Or C code itself will manage it?

**Comment by hcho3** [comment]
@karimkhanvi Treelite will produce C code for the XGBoost model. Preprocessing is not included. You will need to either call the third-party package or re-implement the preprocessing in C.
