### ISSUE TITLE
[BUG] treelite/common.h depends on fmt/format.h but does not install those headers

### ISSUE THREAD

**Issue by teju85** [dmlc/treelite#126]
`treelite/common.h` seems to #include `fmt/format.h` and use it inside [here](https://github.com/dmlc/treelite/blob/master/include/treelite/common.h#L247). However, cmake install command does not include this header. Thus, if one is depending on cmake installed treelite, one will face a compilation error in their project due to unavailable format.h.

**Comment by teju85** [comment]
Tagging @canonizer, JFYI.

Tagging @dantegd, since this is going to block our update of treelite inside [cuML](https://github.com/rapidsai/cuml).

**Comment by teju85** [comment]
yes, that'd be a solution for us, provided it doesn't affect other parts of treelite.
Thanks @hcho3 for a quick response!

**Comment by hcho3** [comment]
@teju85 `fmt::format` is also used in the code generator included in Treelite, but my understanding is that cuML doesn't depend on that part of Treelite. Is that right?

**Comment by teju85** [comment]
another solution could be to install fmt's headers inside treelite's installation?

**Comment by canonizer** [comment]
The cuML library itself doesn't depend on the code generator, but its CI tests do. So having fmtlib's headers available would be strongly preferred.
