### ISSUE TITLE
Issue in Deploying sklearn Random Forest model with Option 2

### ISSUE THREAD

**Issue by akshaykhushu** [dmlc/treelite#134]
Hi, I am new to treelite and was interested in Option 2 of deploying my sklearn model on a linux machine having gcc toolchain. I am exporting my model through 

`model.export_srcpkg(platform='unix', toolchain='gcc', pkgpath='./mymodel.zip', libname='mymodel.so',verbose=True)`

My host machine is running Ubuntu and my target machine also has Ubuntu.
I am also saving the treelite runtime package with

`treelite.save_runtume_package(destdir='.')`

All this code is taken from the documentation page only.  Now, I extract the 2 zip files(one for model and one for treelite runtiume) and try to build the treelite runtime library and that is where I am having issues. When I do:

`cmake ..` 

in the build folder, followed by 

`make`

I get the following error:

`runtime/src/predictor.cc:18:10: fatal error: thread_pool/thread_pool.h: No such file or directory
 #include "thread_pool/thread_pool.h"
compilation terminated.
CMakeFiles/objtreelite_runtime.dir/build.make:114: recipe for target 'CMakeFiles/objtreelite_runtime.dir/src/predictor.cc.o' failed
make[2]: *** [CMakeFiles/objtreelite_runtime.dir/src/predictor.cc.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/objtreelite_runtime.dir/all' failed
make[1]: *** [CMakeFiles/objtreelite_runtime.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

Can anyone help me with this. I have no idea where I am going wrong. The only thing different I did from the documentation page was that I did not do this step:

`model = treelite.Model.load('your_model.model', 'xgboost')` 

Instead, I am importing my sklearn model with:

`model = treelite.gallery.sklearn.import_model(clf)`

**Comment by hcho3** [comment]
It appears that the zip runtime export feature has been broken for a while. I will try to fix it before 1.0 release. For now, you should use Option 1 or 3.

**Comment by hcho3** [comment]
Starting with version 0.92, we offer a separate runtime package `treelite_runtime`. You should be able to run `pip install treelite_runtime`.
