### ISSUE TITLE
Is the package still available on pip?

### ISSUE THREAD

**Issue by trivialfis** [dmlc/treelite#136]
```
pip install treelite
```
results in:
```
ERROR: Could not find a version that satisfies the requirement treelite (from versions: none)
ERROR: No matching distribution found for treelite
```

pip version:
```
pip 19.3.1 python3.7/site-packages/pip (python 3.7)
```

**Comment by hcho3** [comment]
Python 3.7 was not released when last Treelite came out. The issue now is that the wheels were dependent on specific Python versions. I’ll get new release out in next few weeks.

**Comment by trivialfis** [comment]
I see.  Feel free to close this issue. ;-)

**Comment by dehdari** [comment]
Any progress with this?

**Comment by hcho3** [comment]
I compiled new Python wheels for Treelite 0.32 targeting Python 3.7 and 3.8 and uploaded them to PyPI.

**Comment by trivialfis** [comment]
Thanks!

**Comment by hcho3** [comment]
@trivialfis Thanks for taking interest in this project. Admittedly, I have not gotten around to it for a while, there's a lot of technical debt that I need to be paying off. Thankfully, I should have some time to do so over next few weeks.
