### ISSUE TITLE
QST : Advantages of the treelite workflow 

### ISSUE THREAD

**Issue by naveenmiriyalu** [dmlc/treelite#142]
Hi , 

    I would like to understand the benefits behind the current treelite workflow . 
Whats the reason behind choosing to convert the model to a  ".so" file ?
Why not have it in some intermediate format ?
As I observe , we must compile the ".so" file every time the model is trained and then deploy the inference routine. 
![treelite_workflow](https://user-images.githubusercontent.com/4938025/73643073-d6be7200-4698-11ea-9ba2-428a27be7a62.png)

**Comment by hcho3** [comment]
For deploying to edge devices, having a standalone shared library is convenient. Also, there is a performance consideration as well.
