### ISSUE TITLE
Any possibility of using treelite on AWS Lambda?

### ISSUE THREAD

**Issue by jeznag** [dmlc/treelite#147]
Hi, I'm interested in using treelite to perform model building and inference on lambda. The issue is that lambda does not seem to come with gcc or clang. Has anyone figured out a way around this?

**Comment by Htarlov** [comment]
I just did that right now - used lambci/lambda docker image, started it with interactive bash, copied zip generated by treelite there, installed gcc, unzipped and compiled. Then copied back .so files and packed it with my package for lambda function. 
I run those from Python by ctypes - don't want to use scipy, sklearn etc. on lambda as those are big libraries.

One very strange thing - my binary produces results exactly 10 times greater predictions than original model. Same thing happens for all 4 models that I compiled.
Models were RandomForestRegressor.

For example model in Python predicts -0.0353622198733153 but binary model predicts -0.353622198733153

Can live with that, just need to scale it down, but that's strange. I can't tell if it will happen for you. Maybe I did something wrong, not sure.
