### ISSUE TITLE
non C-99 compatible code

### ISSUE THREAD

**Issue by perry-mcmanis** [dmlc/treelite#148]
Hi,
based on the documentation I understand that when I invoke <modelname>.compile() the resulting .c file would be C99 compatible.

Im having trouble compiling the resulting files with GCC or MSVC; the compiler is unhappy with a few of the first lines in the file. If I removed **public status** from the first two function defs and the **inline** keyword from the last, I was able to get it to compile. From here I was able to use it in my VC9.0 project as per the rest of the deploy instructions and get a score for an input of the right shape.  FWIW I used GCC 8.1.0 that would compile, but for this I used the VS 2008 CL compiler which then worked for me later.

```
public static int get_num_output_group() {
    return 1;
  }

  public static int get_num_feature() {
    return 1000;
  }

static inline float pred_transform(float margin) {
  const float alpha = (float)1;
  return 1.0f / (1 + expf(-alpha * margin));
}
```

I was not under the impression that C99 supported public or inline methods.

**Comment by hcho3** [comment]
Which version of Treelite are you using? The `public` keyword was part of a removed feature that produced Java code, and it is no longer part of the latest source.

**Comment by perry-mcmanis** [comment]
0.32, which I installed through pip/PyPI

**Comment by hcho3** [comment]
Try the nightly build, which is built from the latest source:

* Linux 64-bit: [treelite-0.9-py3-none-manylinux1_x86_64.whl.zip](https://github.com/dmlc/treelite/files/4284336/treelite-0.9-py3-none-manylinux1_x86_64.whl.zip)
* Mac OS X: [treelite-0.9-py3-none-macosx_10_8_x86_64.macosx_10_9_x86_64.macosx_10_10_x86_64.macosx_10_11_x86_64.macosx_10_12_x86_64.macosx_10_13_x86_64.macosx_10_14_x86_64.whl.zip](https://github.com/dmlc/treelite/files/4284338/treelite-0.9-py3-none-macosx_10_8_x86_64.macosx_10_9_x86_64.macosx_10_10_x86_64.macosx_10_11_x86_64.macosx_10_12_x86_64.macosx_10_13_x86_64.macosx_10_14_x86_64.whl.zip)
* Windows 64-bit: [treelite-0.9-py3-none-win_amd64.whl.zip](https://github.com/dmlc/treelite/files/4284339/treelite-0.9-py3-none-win_amd64.whl.zip)

I believe the bug should disappear.

**Comment by perry-mcmanis** [comment]
Yeah that output without the keywords, thanks much. Did notice one thing in the nightly build's output:

```
float get_global_bias(void) {
  return nan;
}
```

which also shows up again at the end of the predict function:
`  sum = sum + (float)(nan);`

but my GCC complained about this. Im not great with C but I understand lowercase nan is a function:
https://en.cppreference.com/w/c/numeric/math/nan

when I switched to this constant (float) it worked though:
https://en.cppreference.com/w/c/numeric/math/NAN

Actually FWIW this worked with GCC but not with our ancient MSVC, but that's an us problem.

Thanks for all the help, btw!

**Comment by hcho3** [comment]
I think your model has NaN in the bias term. You should inspect your model and check if it has NaN in it.

**Comment by perry-mcmanis** [comment]
I checked the xgboost binary and if I understand your comment, the base_score is actually set to None, which is a new one to me; I will investigate how it got like that and remedy. Appreciate the heads up.

That's the extent of our challenges with treelite though; Im happy to call this one closed. 

I will also add we are all really happy with Treelite; it's awesome.

**Comment by trivialfis** [comment]
What do you mean by set to None?

**Comment by perry-mcmanis** [comment]
@trivialfis I inherited a trained model binary which works as expected.

I am loading like this and then checking as best as I understood:

```
model = xgb.XGBModel()
model.load_model(model_loc)

print(model.base_score)
```
this prints None

but again, I have no issues predicting with this model or using other xgboost methods. 

I was going to have to retrain anyway so I figured it was just something I wouldn't see again later.

**Comment by trivialfis** [comment]
That's weird, if you do see it again please ping me, I can try to fix it.

**Comment by perry-mcmanis** [comment]
Thanks a ton, I'll let you know if it pops up again when I retrain.
