### ISSUE TITLE
GPU inference?

### ISSUE THREAD

**Issue by Denisevi4** [dmlc/treelite#15]
What do you think of a inference on a GPU? Potentially this could be faster.

**Comment by hcho3** [comment]
@Denisevi4 #67 may make GPU inference more practical. See the RapidScorer paper: https://www.kdd.org/kdd2018/accepted-papers/view/rapidscorer-fast-tree-ensemble-evaluation-by-maximizing-compactness-in-data

**Comment by JohnZed** [comment]
The RAPIDS Forest Inference Library has a treelite front end for GPU inference. See this blog post: https://medium.com/rapids-ai/rapids-forest-inference-library-prediction-at-100-million-rows-per-second-19558890bc35
The released version (0.10) supports XGBoost and LightGBM models, but the newest nightlies can work with treelite protobufs and sklearn RandomForest models as well. For large-batch inference, it's very very fast, though PCI transfers etc. start to add up if you do single-row inference or very small batches.

(Using treelite as a front-end has been awesome to support all these libraries - many thanks to Philip for his work here.)

**Comment by hcho3** [comment]
Please check out RAPIDS cuML, whose GPU-accelerated Forest Inference Library (FIL) integrates with Treelite. Thanks!
