### ISSUE TITLE
convert multi-class xgboost model to lib error

### ISSUE THREAD

**Issue by wuyuanmm** [dmlc/treelite#157]
(the version is 1.0.0 or newer)
I use the python file in ./tests/python directory. I get the error:

 treelite.common.util.TreeliteError: b"[16:57:51] c:\\projects\\treelite-wheels\\treelite\\src\\compiler\\pred_transform.cc:121: Invalid argument given for `pred_transform` parameter. For any task that is NOT multi-class classification, you should set `pred_transform` to one of the following: { 'sigmoid', 'identity', 'exponential', 'logarithm_one_plus_exp',  }" 

whole code is below:

`
import  os
import numpy as np
import treelite
import treelite.runtime
from sklearn.datasets import load_boston, load_iris
from sklearn.model_selection import train_test_split
from util import os_compatible_toolchains, libname, assert_almost_equal

import xgboost

X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test \
    = train_test_split(X, y, test_size=0.2, shuffle=False)
dtrain = xgboost.DMatrix(X_train, label=y_train)
dtest = xgboost.DMatrix(X_test, label=y_test)
param = {'max_depth': 6, 'eta': 0.05, 'num_class': 3, 'silent': 1,
            'objective': 'multi:softmax', 'metric': 'mlogloss'}
num_round = 10
watchlist = [(dtrain, 'train'), (dtest, 'test')]
bst = xgboost.train(param, dtrain, num_round, watchlist)

expected_pred = bst.predict(dtest)

model = treelite.Model.from_xgboost(bst)
libpath = libname('./iris{}')
batch = treelite.runtime.Batch.from_npy2d(X_test)
for toolchain in os_compatible_toolchains():
    model.export_lib(toolchain=toolchain, libpath=libpath,
                    params={}, verbose=True)
    predictor = treelite.runtime.Predictor(libpath=libpath, verbose=True)
    out_pred = predictor.predict(batch)
`

**Comment by danieljyj** [comment]
I have the same error, have you already found the solution?

**Comment by hcho3** [comment]
Please upgrade Treelite to 0.90 or newer: https://pypi.org/project/treelite/#history Thanks!
