### ISSUE TITLE
predict() returns inappropriately shaped result

### ISSUE THREAD

**Issue by wagnew3** [dmlc/treelite#16]
Awesome library--thanks for developing it!

When I'm doing multiclass classification and I call predict on a (1, #features) shaped dataset, I get a (#classes) shaped result, as opposed to a 1x#classes shaped result. This forces me to write code to handle this case, as predictions on all other sizes return 2D results (ex. (100x, #features) returns a (100, #classes) shaped result).

**Comment by hcho3** [comment]
I went ahead and added a line to re-shape the result appropriately for multi-class classification. Thanks!
