### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by xcTorres** [dmlc/treelite#161]
Process finished with exit code 132 (interrupted by signal 4: SIGILL)

**Comment by hcho3** [comment]
Did you run `export_lib` or `export_srcpkg`? 

To work around the error, you can use `compile()` to obtain the C code and compile it yourself.

**Comment by xcTorres** [comment]
Thanks for answering. Both export_lib and export_srcpkg will report this error.

**Comment by hcho3** [comment]
It looks like `subprocess` module in Python is not working on your machine. I have no idea how this issue can be fixed. You should use `compile()` to get the C code directly.

**Comment by xcTorres** [comment]
Got it. I am going to try it.

**Comment by xcTorres** [comment]
compile also cannot be run on Mac OS. But export and compile can be run on Docker Linux System.
