### ISSUE TITLE
Ill-formed LightGBM model file: leaf_count cannot be empty string

### ISSUE THREAD

**Issue by itssimon** [dmlc/treelite#168]
I'm getting the following error when trying to load a LightGBM model:

```
TreeliteError: [21:43:22] ../src/frontend/lightgbm.cc:258: Check failed: !it->second.empty() Ill-formed LightGBM model file: leaf_count cannot be empty string
```

It appears that some saved LightGBM models have empty trees and others don't. Below is a snippet from a model file that does:

```
Tree=2142
num_leaves=1
num_cat=0
split_feature=
split_gain=
threshold=
decision_type=
left_child=
right_child=
leaf_value=0
leaf_weight=
leaf_count=
internal_value=
internal_weight=
internal_count=
shrinkage=1
```

This model was saved using LightGBM version 2.3.1 (most current).

Can this be handled in treelite?

**Comment by hcho3** [comment]
I'll take a look.

**Comment by itssimon** [comment]
Thanks for fixing this @hcho3! Any chance to you could release this fix soon?
