### ISSUE TITLE
Questions about mimum requirements of treelite

### ISSUE THREAD

**Issue by akshaykhushu** [dmlc/treelite#183]
What is the minimum python version requirements(if any) for treelite. I am running it on python3.6 on ubuntu 16.04. I am not able to install it with python-pip

**Comment by hcho3** [comment]
We require Python 3.6+ and Pip 19.0+.

**Comment by hcho3** [comment]
Treelite is also available on conda:

conda install -c conda-forge treelite

**Comment by hcho3** [comment]
I just tried installing Treelite using AWS EC2 instance running Ubuntu 16.04. Upgrading Pip did the trick.
