### ISSUE TITLE
Is it possible to apply treelite_runtime without compiling model

### ISSUE THREAD

**Issue by gavrmike** [dmlc/treelite#190]
Hi!
I have few lightgbm models.  
Each has size ~100mb. I would like to convert it into protobuf, and after use it (apply model for getting predictions) without compiling(main.c file has very huge size around 1gb). Is it possible?

**Comment by hcho3** [comment]
No it is not possible currently. You should use LightGBM package directly.

**Comment by gavrmike** [comment]
@hcho3 are you planning to add this?

**Comment by hcho3** [comment]
No. I do not.
