### ISSUE TITLE
Random high CPU usage in a container based environment

### ISSUE THREAD

**Issue by SuganPrabu96** [dmlc/treelite#220]
We use Kubernetes and the treelite runtime Python API for serving tree based models in production using the [Predictor.predict method](https://treelite.readthedocs.io/en/latest/treelite-runtime-api.html#treelite_runtime.Predictor.predict)
We observed high CPU usage on some replicas of our service randomly while the others were fine. Initially, I thought it was due to thread pinning of treelite so I set the environment variable TREELITE_BIND_THREADS=0. I also set the environment variable OMP_NUM_THREADS=1 to disable multithreading with OpenMP. But I still occasionally face the same issue and it happens very randomly. The load handled by each replica of the service seems to be the same but just the CPU usage is high which leads to a significant increase in the latency. Moreover, all the problematic replicas seem to be running on the same node (machine) which led me to think that there is some other knob which is pinning threads to a processor somewhere.

@hcho3 It would be very helpful if you could look into this issue asap since we are facing this issue in our production service.

**Comment by hcho3** [comment]
@SuganPrabu96 I have no idea what's causing the high CPU usage. One possible cause is that the thread pool uses busy waiting to wait for tasks. Try changing the value of `spin_count` to 0 in the following line:
https://github.com/dmlc/treelite/blob/303fd4f50e409653d6e914607ff5d0fc4b9979d6/src/predictor/thread_pool/spsc_queue.h#L46

so that waiting threads will always go to sleep instead of busy waiting.

**Comment by SuganPrabu96** [comment]
@hcho3 I see, I think that could be a possible reason too. Is it possible to set it from the Python runtime API? And can it be overridden using [OMP_WAIT_POLICY](https://www.openmp.org/spec-html/5.0/openmpse55.html)?

**Comment by hcho3** [comment]
@SuganPrabu96 No, since Treelite uses a custom thread pool and does not rely on OpenMP. You will need to recompile Treelite.

**Comment by SuganPrabu96** [comment]
@hcho3 I also noticed that if I don't set nthread when I create Predictor instance in the Python runtime API, by default it uses all available hardware threads.
https://github.com/dmlc/treelite/blob/mainline/runtime/python/treelite_runtime/predictor.py#L100
https://github.com/dmlc/treelite/blob/mainline/src/predictor/predictor.cc#L349

This is why I set OMP_NUM_THREADS to 1, but could you confirm if this is actually used? Do I need to set the threads manually as well?

Edit: Just noticed your message above :)

**Comment by hcho3** [comment]
Please set nthread manually. Treelite doesn't respect OMP_NUM_THREADS.

**Comment by SuganPrabu96** [comment]
Got it! I think my service is trying to use more threads than the available number of CPUs which is causing some problems. Let me trying setting nthreads manually. Also, does `spin_count` matter if I want to set `nthreads=1`?

**Comment by hcho3** [comment]
Try setting `nthread=1` first (this won't require recompiling). If that doesn't fix the problem, then try disabling busy waiting.

**Comment by SuganPrabu96** [comment]
Thank you so much for responding quickly! Let me try setting `nthread=1` at first.

**Comment by hcho3** [comment]
@rlagur9286  This might be relevant to you.
