### ISSUE TITLE
Treelite C API gives an unexpected result

### ISSUE THREAD

**Issue by zl45556264** [dmlc/treelite#221]
Hello,

We just encountered an unexpected result in the prediction with Treelite C API.

We did get a model from python xgboost, and then export it as a dynamic library(.so) with treelite package. Indeed we know that in old versions xgboost in python will give different results between the list input and numpy.array input. See https://discuss.xgboost.ai/t/different-results-in-predictions-with-numpy-array-and-list/1934/3.

In our case, the C API just gave a prediction which was the same as python prediction with list input. What is the key point to make a correct prediction? Maybe a little information of how we did the prediction is important, here it is.
 - construct float array factor_values[178]={}
 - convert it into densebatch with TreeliteAssembleDenseBatch (Shoud I use SparseBatch?)
 - make prediction with TreelitePredictorPredictBatch

BTW, we have made correct predictions before with another dynamic library exported from a xgboost model. And we cannot specify the difference between these two models at the moment.

We will very appreciate your kind help！

Thanks
Lei

**Comment by hcho3** [comment]
Are you able to post your model?

**Comment by zl45556264** [comment]
sure, but model files are big . Can I sent them to your email? Otherwise how should I proceed?

**Comment by hcho3** [comment]
Sure, send me an email at chohyu01@cs.washington.edu

**Comment by zl45556264** [comment]
Hi, email sent out and models are attached.

Here p1.dat was trainded model with xgboost.train(), and p1.so was generated by treelite package from xgboost.

Yesterday, we re-trained the model with xgboost.Regressor.fit() and this model met the same issue. However, when we added 1e-32 into the feature values (because there are a lot of zeros in the values, i.e. float 0.0), treelite C API generated the correct prediction as python did. This does not work for a xgboost.train() model.

In both of the trainings above, all nan were replaced with 0.

**Comment by hcho3** [comment]
@zl45556264 I received your model and was able to load it on my machine. Unfortunately, I could not reproduce the problem. Both XGBoost and Treelite yield the same prediction:
```
XGBoost: [0.08755532]
Treelite: 0.08755532
```

I ran this Python program:
```python
import xgboost as xgb
import treelite
import treelite_runtime
import numpy as np

model = treelite.Model.load('p1.model', model_format='xgboost')
model.export_lib('gcc-9', 'compiled.dylib', params={'parallel_comp': model.num_tree}, verbose=True)

bst = xgb.Booster(model_file='p1.model')
X = np.array([[0.0] * 178], dtype=np.float32)
dmat = xgb.DMatrix(X)
print(f'XGBoost: {bst.predict(dmat)}')

predictor = treelite_runtime.Predictor(libpath='./compiled.dylib')
dmat = treelite_runtime.Batch.from_npy2d(X)
print(f'Treelite: {predictor.predict(dmat)}')
```

**Comment by zl45556264** [comment]
Hello,

Thanks for your reply and test case.

What confused us is the prediction of Treelite C API, but not Treelite prediction in python. With the model for C API (p1.so dynamic library), C API prediction on { 0. } * 178 may not be correct but on { 1.e-32} * 178 is correct. Here we say a prediction value is correct when it is the same as the prediction on { 0. } * 178  with python package XGBoost/Treelite.

I don't know whether the difference is caused by p1.so itself which is exported from p1.model, or by numerical precision in C API (different precisions lead to different results in </<=/... ).

Indeed we can almost get the predictions we want  by adding 1.e-32 into feature values with C API.

Thanks

**Comment by hcho3** [comment]
@zl45556264 Can you post your C++ application code that uses the Treelite's C API? I want to check whether it's using the C API correctly. The Treelite Python package is using the C API underneath, so if the Python package produces the correct prediction, it should be possible to write the C API so as to obtain the correct prediction.

**Comment by zl45556264** [comment]
Here it is.

```cpp
#include "../runtime/native/include/treelite/c_api_runtime.h"
#include <iostream>
#include <sys/time.h>
#include <math.h>

using namespace std;

int pred()
{
    float __nan = 0.0;
    float __factor_values[178];
    
    for (int i=0; i < 178; i++)
    {
        // __factor_values[i] = 1.e-32;
        __factor_values[i] = 0.;
    }

    int __test_rows = 1;
    int __test_cols = 178;

    DenseBatchHandle batch;
    TreeliteAssembleDenseBatch(__factor_values, __nan, (size_t)__test_rows, (size_t)__test_cols, &batch);

    size_t size = 0;


    // ==========================================================================
    PredictorHandle predictor_a;
    TreelitePredictorLoad("../../model_regressor/p3.so", 2, &predictor_a);
    
    float predictions_a[__test_rows];
    TreelitePredictorPredictBatch(predictor_a, batch, 0, 0, 0, predictions_a, &size);
    cout << "predictions_a: " << predictions_a[0] << endl;

}



int main()
{
    for (int i=0; i < 10; i++)
    {
        pred();
    }

    return 0;
}
```

**Comment by hcho3** [comment]
Please revise this line
```cpp
float __nan = 0.0;
```
to
```cpp
float __nan = std::numeric_limits<float>::quiet_NaN();
```
With this revision, you'll be able to obtain the correct prediction.

**Comment by zl45556264** [comment]
yes, it works in my case. Thanks a lot!

**Comment by shahidzk1** [comment]
@hcho3 I am also having an issue that my python score and treelite c score don't match. Could you please have a look at my C/C++ code to check whether I am doing the missing entries correctly?
`void treelite(TString name) {
  
   fstream newfile;
   newfile.open(name,ios::in); 
   std::string tp;
   getline(newfile, tp);
   //tp.pop_back();
   //tp.erase(tp.begin());
   TString a(tp);
  

  TFile* f = TFile::Open(a.Data(), "UPDATE");
  
  Float_t  Candidates_chi2_geo, Candidates_chi2_prim_first, Candidates_chi2_prim_second, Candidates_distance, Candidates_l_over_dl, Candidates_mass, Candidates_pT, Candidates_rapidity, Candidates_generation, Candidates_plain_M, Candidates_plain_pid, Candidates_plain_mass2_first, Candidates_plain_mass2_second, Candidates_p;


  TTree *t1 = (TTree*)f->Get("plain_tree");
  
  t1->SetBranchAddress("Candidates_plain_chi2_geo",&Candidates_chi2_geo);
  t1->SetBranchAddress("Candidates_plain_chi2_prim_first",&Candidates_chi2_prim_first);
  t1->SetBranchAddress("Candidates_plain_chi2_prim_second",&Candidates_chi2_prim_second);
  t1->SetBranchAddress("Candidates_plain_distance",&Candidates_distance);
  t1->SetBranchAddress("Candidates_plain_l_over_dl",&Candidates_l_over_dl);
  t1->SetBranchAddress("Candidates_plain_mass",&Candidates_mass);
  t1->SetBranchAddress("Candidates_plain_pT",&Candidates_pT);
  t1->SetBranchAddress("Candidates_plain_rapidity",&Candidates_rapidity);
  t1->SetBranchAddress("Candidates_plain_generation",&Candidates_generation);
  t1->SetBranchAddress("Candidates_plain_M",&Candidates_plain_M);
  t1->SetBranchAddress("Candidates_plain_pid",&Candidates_plain_pid);
  t1->SetBranchAddress("Candidates_plain_mass2_first",&Candidates_plain_mass2_first);
  t1->SetBranchAddress("Candidates_plain_mass2_second",&Candidates_plain_mass2_second);
  t1->SetBranchAddress("Candidates_plain_p",&Candidates_p);
  
  TFile f1("BDT_selected_candidates.root","recreate");
  TTree t2("t_BDT","BDT_selected_candidates");
  
  float pT, rapidity, mass, BDT_score, multiplicity, chi2_geo, prim_first, prim_second,distance, l_over_dl, mass2_first, mass2_second; Int_t issignal;
   t2.Branch("pT",&pT,"pT/F");          t2.Branch("rapidity",&rapidity,"rapidity/F"); t2.Branch("BDT_score",&BDT_score,"BDT_score/F");
   t2.Branch("mass",&mass,"mass/F");    t2.Branch("issignal",&issignal,"issignal/I"); 
   t2.Branch("multiplicity",&multiplicity,"multiplicity/F");
   t2.Branch("chi2_geo",&chi2_geo,"chi2_geo/F");          t2.Branch("prim_first",&prim_first,"prim_first/F"); t2.Branch("prim_second",&prim_second,"prim_second/F");
   t2.Branch("distance",&distance,"distance/F");    t2.Branch("l_over_dl",&l_over_dl,"l_over_dl/F"); 
   t2.Branch("mass2_first",&mass2_first,"mass2_first/F");    t2.Branch("mass2_second",&mass2_second,"mass2_second/F"); 
  
  
  std::vector<float> output{};
  
  const long n_entries = t1->GetEntries();
  output.reserve(n_entries);

  const size_t n_features = get_num_feature();
  union Entry input[n_features];
  
  float probab;
  TBranch *bpt = t1->Branch("probab",&probab,"probabilities");
  t1->SetBranchAddress("probab",&probab);
  

  for (long i = 0; i < n_entries; i++)
   {
     t1->GetEntry(i);
     
    
    if( (Candidates_generation>=1)  && (Candidates_plain_M>200) && (Candidates_plain_M<400)  && (Candidates_pT<0.6) && (Candidates_rapidity<1.6) && (Candidates_mass>1.076) && (Candidates_mass<1.2) && (Candidates_plain_pid>1000) ){ 
    input[0].fvalue = Candidates_chi2_geo;
    input[1].fvalue = Candidates_chi2_prim_first;
    input[2].fvalue = Candidates_chi2_prim_second;
    input[3].fvalue = Candidates_distance;
    input[4].fvalue = Candidates_l_over_dl;
    if (  Candidates_plain_mass2_first  == std::isnan(2)   ){input[5].missing = -1; input[5].fvalue = Candidates_plain_mass2_first; }
    if (  Candidates_plain_mass2_second == std::isnan(2)  ){input[6].missing = -1; input[6].fvalue = Candidates_plain_mass2_second;}
    if (  Candidates_plain_mass2_first  != std::isnan(2)   ){input[5].fvalue = Candidates_plain_mass2_first;    }
    if ( Candidates_plain_mass2_second  != std::isnan(2)   ){input[6].fvalue = Candidates_plain_mass2_second;    }
    
    output.push_back(predict(input, 0));
    probab= output.at(i);

      if( (probab >= .0) )
    
    {
      
      pT=Candidates_pT;  mass= Candidates_mass; rapidity=Candidates_rapidity;issignal=Candidates_generation; 
      BDT_score=probab; 
      multiplicity = Candidates_plain_M;
      t2.Fill();
    }
    }
     
  }
  t2.Write();
}`
