### ISSUE TITLE
How to deploy in C++

### ISSUE THREAD

**Issue by maudzung** [dmlc/treelite#238]
Thanks for your great work. I tested the lib in Python, it's faster than the pure `LightGBM` lib.
I'm trying to implement it in C++. Are there any available examples for C++ implementation?

**Comment by maudzung** [comment]
My simple code in C++

```
extern "C" {
#include <treelite/c_api.h>
#include <treelite/c_api_runtime.h>
}

int main() {
  PredictorHandle predictor; 
  TreelitePredictorLoad("./mymodel.so", 2, &predictor);
    return 0;
}
```

The `CMakeLists.txt`

```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(test_treelite_project)
set(treelite_INCLUDE_DIRS /usr/local/include)
find_library(treelite_LIBS NAMES libtreelite.so libtreelite_runtime.so libtreelite_static.a libtreelite_runtime_static.a PATHS /usr/local/lib/)
add_executable(app_treelite test_treelite.c)
target_link_libraries(app_treelite ${treelite_LIBS})
target_include_directories(app_treelite PRIVATE ${treelite_INCLUDE_DIRS})
set_property(TARGET app_treelite PROPERTY CXX_STANDARD 14)
```

However, I faced the compile error: `undefined reference to "TreelitePredictorLoad"`. I already copied the `libtreelite.so libtreelite_runtime.so libtreelite_static.a libtreelite_runtime_static.a` to `/usr/local/lib/`, and `include/treelite/` to `/usr/local/include/treelite`

Can you please help me?

**Comment by hcho3** [comment]
@maudzung Take a look at the CMakeLists.txt of cuML, which links with Treelite.

1. Run `make install` in the build directory of Treelite:
```
cd treelite
mkdir build
cd build
cmake ..
make install
```
This will install the library files (`*.so`) as well as the CMake configuration files necessary for step 2.

2. Use `find_package(Treelite)` to locate the installed copy of Treelite:
```cmake
find_package(Treelite 0.93 REQUIRED)
```
https://github.com/rapidsai/cuml/blob/ae7e4442a3dccdf6c360bd7d20248c69cd706fb2/cpp/cmake/Dependencies.cmake#L188

3. Use `target_link_libraries` to link with CMake targets `treelite::treelite` and `treelite::treelite_runtime`:
```cmake
target_link_libraries(${CUML_CPP_TARGET} PRIVATE treelite::treelite treelite::treelite_runtime)
```
https://github.com/rapidsai/cuml/blob/ae7e4442a3dccdf6c360bd7d20248c69cd706fb2/cpp/CMakeLists.txt#L351-L352

**Comment by maudzung** [comment]
Thank you so much. It works for me now.
However, the speed is not better than python code, and the runtime is also unstable. Do you have any suggestions for me to boost the speed?

```cpp
#include <iostream>
#include <limits>
#include <vector>
#include <time.h>

extern "C" {
#include <treelite/c_api.h>
#include <treelite/c_api_runtime.h>
}

#define CHECK_CALL(x) if ( (x) == -1 ) { fprintf(stderr, "%s", #x); exit(-1); }

int main() {
    std::cout << "Testing treelite usage" << std::endl;

    PredictorHandle predictor;
    CHECK_CALL(TreelitePredictorLoad("./mymodel.so", 4, &predictor));

    float __nan = std::numeric_limits<float>::quiet_NaN();
    int nrows = 100;
    int nfeats = 45;
    int num_classes= 4;
    float* feats_data = static_cast<float*>(calloc(nrows * nfeats, sizeof(float)));

    

    DenseBatchHandle batch;
    CHECK_CALL(TreeliteAssembleDenseBatch(feats_data, __nan, (size_t)nrows, (size_t)nfeats, &batch));

    float* predictions = (float*)malloc(nrows * num_classes * sizeof(float));

    size_t size;
    for (int loop_idx = 0; loop_idx < 100; loop_idx++) {
        clock_t start = clock();
        CHECK_CALL(TreelitePredictorPredictBatch(predictor, batch, 0, 0, 0, predictions, &size));
        clock_t end = clock();
        float elapsed_time = ((float)(end - start) / 1000000.0F) * 1000; 
        std::cout << "loop_idx: " << loop_idx << ", time: " << elapsed_time << " ms" << std::endl;
    }

    return 0;
}
```

**Comment by hcho3** [comment]
> and the runtime is also unstable

Can you be more specific? Do you see a crash, or do you mean a high variance in the measured time for prediction?

As for boosting prediction speed, you may consider using the compiled model directly and eschew the Treelite runtime entirely. See https://treelite.readthedocs.io/en/latest/tutorials/deploy.html#prediction-instructions

**Comment by maudzung** [comment]
Thank you so much, it works better now.
One problem occurs when my program has  more than 2 lightgbm models (2 libs). The compiler will raise an error: `previous definition of union Entry`. Hence, I fixed it by adding the following macro:
```cpp
#ifndef TREELITE_COMPILER_COMMON_H_
#define TREELITE_COMPILER_COMMON_H_
union Entry {
  int missing;
  float fvalue;
  int qvalue;
};

struct Node {
  uint8_t default_left;
  unsigned int split_index;
  float threshold;
  int left_child;
  int right_child;
};

#endif  // TREELITE_COMPILER_COMMON_H_
```

Do you have other suggestions to solve it? Many thanks.

**Comment by hcho3** [comment]
The include guard looks reasonable to me

**Comment by marsupialtail** [comment]
When you link against the mymodel.so directly, how do you enable multithreading? Maybe I'll make a separate issue.
