### ISSUE TITLE
Remove dmlc-core dependency

### ISSUE THREAD

**Issue by hcho3** [dmlc/treelite#244]
The dmlc-core dependency creates a potential conflict with other packages that use dmlc-core, e.g. XGBoost. Since Treelite is a relatively lightweight package, it should drop the dmlc-core dependency.

**Comment by ajschmidt8** [comment]
@hcho3, just checking in on this issue. Are there any updates regarding its progress?

**Comment by hcho3** [comment]
@ajschmidt8 I'll try to get to it before July 1.

**Comment by hcho3** [comment]
#285 will remove dmlc-core.
