### ISSUE TITLE
My model doesn't work even on the example given for C 

### ISSUE THREAD

**Issue by shahidzk1** [dmlc/treelite#248]
When I try to deploy my model in C by using the example in https://treelite.readthedocs.io/en/latest/tutorials/deploy.html, it shows the following error:
/usr/bin/ld: mymodel.so: undefined reference to `expf'
collect2: error: ld returned 1 exit status

**Comment by hcho3** [comment]
You should add `-lm` linker flag when building the library.

**Comment by shahidzk1** [comment]
@hcho3 I am not an expert on C and C++ so could you please be more specific? With the following python code I create the library

import treelite
model = treelite.Model.from_xgboost(bst)
toolchain = 'gcc'
model.export_lib(toolchain=toolchain, libpath='./mymodel.so',
                 params={'parallel_comp': 8}, verbose=True)
platform = 'unix'
toolchain = 'gcc'
model.export_srcpkg(platform=platform, toolchain=toolchain,
                    pkgpath='./mymodel.zip', libname='mymodel.so',
                    verbose=True)

I unzip it and then I use make command

**Comment by hcho3** [comment]
Can you post the content of the Makefile?

**Comment by shahidzk1** [comment]
mymodel.so: main.o
        gcc -shared -O3 -o mymodel.so main.o -std=c99 
main.o: main.c
        gcc -c -O3 -o main.o main.c -fPIC -std=c99 
~

**Comment by shahidzk1** [comment]
Finally I use the following command
gcc -o myprog myprog.c mymodel.so -I. -std=c99

**Comment by hcho3** [comment]
You should revise the Makefile as follows:
```
mymodel.so: main.o
	gcc -shared -O3 -o mymodel.so main.o -std=c99 -lm
main.o: main.c
	gcc -c -O3 -o main.o main.c -fPIC -std=c99
```

**Comment by shahidzk1** [comment]
changed it to 
mymodel.so: main.o
        gcc -shared -O3 -o mymodel.so main.o -std=c99 -lm 
main.o: main.c
        gcc -c -O3 -o main.o main.c -fPIC -std=c99 
~                                                      

saved, tried it again, doesn't work. Tried make again but doesn't work

**Comment by hcho3** [comment]
You should also fix the command for building your program. Use: `gcc -o myprog myprog.c mymodel.so -I. -std=c99 -lm`

**Comment by shahidzk1** [comment]
@hcho3 doesn't show any error now but doesn't print anything may be it is the selection cuts doing so. Mate do you have a gitlab account? I am a PhD student of high energy physics and the problems I face are more severe but I tried to implement my model on the example that you have given.

**Comment by hcho3** [comment]
It appears that your issue is not related to Treelite any more. Can I close this issue?

**Comment by shahidzk1** [comment]
When I implement my model on my own code, the following issue appears, so I didn't know what to do but tried my model on your model example.
IncrementalExecutor::executeFunction: symbol '_Z7predictP5Entryi' unresolved while linking [cling interface function]!
You are probably missing the definition of predict(Entry*, int)
Maybe you need to load the corresponding shared library?

**Comment by shahidzk1** [comment]
This is the msg that I get on my code
`IncrementalExecutor::executeFunction: symbol '_Z7predictP5Entryi' unresolved while linking [cling interface function]!
You are probably missing the definition of predict(Entry*, int)
Maybe you need to load the corresponding shared library?
`

**Comment by hcho3** [comment]
It appears that Cling is having trouble locating the dynamic library that contains the prediction code. To fix the problem easily, you should just copy and paste the generated C code (`main.c`) into your C++ program. Make sure to copy the content of `main.c` as well as `header.h`.

**Comment by shahidzk1** [comment]
No I am not using a notebook but I am using Root (the C++ based program by CERN). That code is 3711 lines long, the guys at Alice experiment have done the same and it works for them. Somehow on my code it shows this error. I belong to another experiment. 

The code that I use is

`#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TH1F.h"
#include <vector>
#include "TString.h"
#include "TMath.h"
#include "TH1.h"
#include "TF1.h"
#include "TLegend.h"
#include "TCanvas.h"

#include <stdio.h>
#include <stdlib.h>
#include "mymodel.h"


// union Data {
//   int unused;
//   float data;
// };  

void python_to_root(){
  TCanvas* c1 = new TCanvas();
  c1->Divide(2,1);
  
  c1->cd(1);
  
  /* Open the root file*/
  TFile *f = new TFile("/home/shahid/cbmsoft/pf_simple/build/AnalysisTreeInterface/10k_events_PFSimplePlainTree.root","READ");
  TTree *t1 = (TTree*)f->Get("PlainTree");
  
  Float_t  LambdaCandidates_chi2primneg, LambdaCandidates_chi2primpos, LambdaCandidates_ldl, LambdaCandidates_distance, LambdaCandidates_chi2geo;
  
  t1->SetBranchAddress("LambdaCandidates_chi2primneg",&LambdaCandidates_chi2primneg);
  t1->SetBranchAddress("LambdaCandidates_chi2primpos",&LambdaCandidates_chi2primpos);
  t1->SetBranchAddress("LambdaCandidates_ldl",&LambdaCandidates_ldl);
  t1->SetBranchAddress("LambdaCandidates_distance",&LambdaCandidates_distance);
  t1->SetBranchAddress("LambdaCandidates_chi2geo",&LambdaCandidates_chi2geo);
  
  
  
  std::vector<float> output{};
  
  const long n_entries = t1->GetEntries();
  output.reserve(n_entries);

  const size_t n_features = 5;
  union Entry input[n_features];

  for(long i=0; i<n_entries; ++i){
    
    input[0].fvalue = LambdaCandidates_chi2primneg;
    input[1].fvalue = LambdaCandidates_chi2primpos;
    input[2].fvalue = LambdaCandidates_ldl;
    input[3].fvalue = LambdaCandidates_distance;
    input[4].fvalue = LambdaCandidates_chi2geo;
    
    output.push_back(predict(input, 0));
  }
  
  TH1F *h = new TH1F("h_prob", "This is the probability distribution", 300, 0, 1);

  for(auto prob : output){
    h->Fill(prob);
  }
  
  h->Draw();
    
}
`

**Comment by hcho3** [comment]
@shahidzk1 I don't think I have sufficient background to debug your program. For now, please try my suggestion of copying the content of `header.h` and `main.c` into your C++ source file.

**Comment by shahidzk1** [comment]
@hcho3 okay let me do it

**Comment by shahidzk1** [comment]
@hcho3 great man it works now, but code is too long. Is there any other way with which I can connect my main.c and header.h with my code? Thanks a lot for your help! I highly appreciate it, if you were in Germany I would have taken you out for a cup of coffee or something

**Comment by hcho3** [comment]
You can create a separate file `model.c` to hold the content of main.c and header.h and then add `#include "model.c"` in your main program. That way, you can keep your model short.
