### ISSUE TITLE
toolchain not found

### ISSUE THREAD

**Issue by coderliuhao** [dmlc/treelite#252]
I've install  MinGW and added it to my system environment variable on Win10 ,but  when I run a python script in my conda env with python 3.8.5,it raised" ValueError: Toolchain gcc not found. Ensure that it is installed and that it is a variant of GCC or Clang" if I set toolchain "gcc"

**Comment by hcho3** [comment]
Treelite does not support the use of MinGW with `export_lib`. You have two options:
1. Use Visual Studio, by specifying `toolchain='msvc'`
2. Use `compile()` to obtain the C source code and then manually build it with MinGW

**Comment by coderliuhao** [comment]
> Treelite does not support the use of MinGW with `export_lib`. You have two options:
> 
> 1. Use Visual Studio, by specifying `toolchain='msvc'`
> 2. Use `compile()` to obtain the C source code and then manually build it with MinGW

I've  changed  toolchain as you suggested,and I changed my model format from .so to  .dll,but It always raise 
![](https://gitee.com/drunkcoderliuhao/my_picbed/raw/master/img/20210213124130.png)
Code as follows:
```
import treelite
import treelite_runtime
import xgboost as xgb
import numpy as np
from sklearn.datasets import make_classification
from sklearn import model_selection
from matplotlib import pyplot as plt
import time

X,y = make_classification(n_samples=100000,n_features=1000)
xtrain,xvalid,ytrain,yvalid = model_selection.train_test_split(X,y,test_size=0.2)

dtrain = xgb.DMatrix(xtrain,label=ytrain)
dvalid = xgb.DMatrix(xvalid,label=yvalid)
params = {"max_depth":5,"objective":"reg:squarederror","eval_metric":"rmse"}

xgbmodel = xgb.train(params,dtrain,num_boost_round=10,evals=[(dtrain,"train"),(dvalid,"validation")])

model = treelite.Model.from_xgboost(xgbmodel)
toolchain = "msvc"
model.export_lib(toolchain=toolchain,libpath=r"F:\Learning_notes\博客文章学习\treelite_test\model_compiler\model.dll")

predictor = treelite_runtime.Predictor(r"F:\Learning_notes\博客文章学习\treelite_test\model_compiler\model.dll",verbose=True)

nrows = [1000,10000,100000,200000]
xgb_time=[]
treelite_time=[]

for nrow in nrows:
    data = np.random.random((nrow,1000))
    dt = xgb.DMatrix(data)

    begin =time.time()
    _ = xgbmodel.predict(dt)
    xgb_time.append(time.time()-begin)

    batch = treelite_runtime.Batch.from_npy2d(data)

    begin2 = time.time()
    _ = predictor.predict(batch)
    treelite_time.append(time.time()-begin2)

fig,ax = plt.subplots(1,1,figsize=(8,5))

ax.plot(nrows,xgb_time,c = "b",label="xgb")
ax.plot(nrows,treelite_time,c = "r",label="treelite")
ax.legend(loc="upper left")
plt.show()
```

**Comment by hcho3** [comment]
It looks like there's a problem in the system locale. I have no idea how to fix the problem. Please use `compile()` for now
