### ISSUE TITLE
Treelite4j

### ISSUE THREAD

**Issue by li-yazhou** [dmlc/treelite#253]
Please, How to get a full libpath?  Can treelite4j  be applied to production environment for Xgboost？

![image](https://user-images.githubusercontent.com/17548940/108341558-ba926200-7214-11eb-907d-83ce60ca3311.png)

**Comment by hcho3** [comment]
Please use the Treelite Python package to generate a .so library first. See https://treelite.readthedocs.io/en/latest/tutorials/first.html
