### ISSUE TITLE
Execute two different  XGBoost models in the C++ project

### ISSUE THREAD

**Issue by m-boris** [dmlc/treelite#254]
I create two C classes using the "Treelite" python generator to execute the XGBoost in the C++ project.
I can execute only one XGBoost file due to the same method names for the predict function.
The possible solution can be wrapping the code inside a namespace.
Is it possible to add this functionality to the Python generator?

**Comment by hcho3** [comment]
No, the code generator will only produce C99 code. Please manually revise the generated code to add a namespace.
