### ISSUE TITLE
[QST] How to perform batch prediction with a treelite_runtime Predictor object?

### ISSUE THREAD

**Issue by rickyhuw** [dmlc/treelite#256]
![image](https://user-images.githubusercontent.com/38985786/110295656-52bd8300-802c-11eb-9c5d-e0fa3f61c9bd.png)

**Comment by wphicks** [comment]
As you can see in the `treelite_runtime` [API documentation](https://treelite.readthedocs.io/en/latest/treelite-runtime-api.html), there is no `Batch` class in that module. I believe you're probably looking for `DMatrix`, which is documented [here](https://treelite.readthedocs.io/en/latest/treelite-runtime-api.html#treelite_runtime.DMatrix) and which is typically [the first argument](https://treelite.readthedocs.io/en/latest/treelite-runtime-api.html#treelite_runtime.Predictor.predict) to `predict` calls.

**Comment by hcho3** [comment]
@rickyhuw The examples in the documentation had some outdated uses of the runtime API. I filed #257 to update the examples. Sorry for the inconvenience.
