### ISSUE TITLE
Errors when getting dump from the xgboost model exported from treelite

### ISSUE THREAD

**Issue by jamesliu** [dmlc/treelite#26]
model.export_as_xgboost(local_model, name_obj="reg:linear")
bst = xgboost.Booster()
bst.load_model(local_model)
trees = bst.get_dump(with_stats=True, dump_format='json')
for tree in trees:
    print(tree)
    json.loads(tree)

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-56-6150861d1886> in <module>()
      2 for tree in trees:
      3     print(tree)
----> 4     json.loads(tree)

~/anaconda/envs/g/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

~/anaconda/envs/g/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

~/anaconda/envs/g/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 113 (char 112)

**Comment by Denisevi4** [comment]
I don't experience this problem

**Comment by Denisevi4** [comment]
Actually, I do experience this problem now with a different dataset. 

In the exported model the model feature names and their types are not set So, I can't dump the model. I have to set them manually after export_as_xgboost

**Comment by hcho3** [comment]
`export_as_xgboost()` will be moved to experimental branch, so that development efforts can be focused to core features.
