### ISSUE TITLE
The system crashed

### ISSUE THREAD

**Issue by rickyhuw** [dmlc/treelite#262]
When using the lightgbm model, it will get stuck when the amount of requests is large. At the same time, the system load will continue to increase. It seems that the CPU is suspended somewhere

**Comment by wphicks** [comment]
Can you give us a bit more detail? What size model are you working with? When you say "the amount of requests is large," what exactly does that mean? What sort of environment are you in, and how did you install Treelite?

**Comment by hcho3** [comment]
Feel free to try GTIL: https://treelite.readthedocs.io/en/latest/treelite-api.html#treelite.gtil.predict
