### ISSUE TITLE
a possible faster version of predict single row 

### ISSUE THREAD

**Issue by 7starsea** [dmlc/treelite#267]
My typical use case is online real-time prediction, predict one row at a time and sample code is like
```
float TreeLiteShannonPredictor::predict(const double * values, const int cols){
    //// const int rows=1
    std::size_t out_len = 0;
    float out_result;

    DMatrixHandle dmat;
    safe_treelite(TreeliteDMatrixCreateFromMat(values, "float64",  1, cols, "nan", &dmat));

    safe_treelite(TreelitePredictorPredictBatch(predictor_, dmat, 0, 0,  &out_result, &out_len));

    safe_treelite(TreeliteDMatrixFree(dmat));
    return out_result;
}
```
Since every call of predict would involve a creation and deletion of DMatrixHandle, I am wondering whether we could cache the DMatrixHanle to save prediction time. (LightGBM provides two apis (LGBM_BoosterPredictForMatSingleRowFastInit/LGBM_BoosterPredictForMatSingleRowFast to achieve this kind of task.)

Thanks.

**Comment by hcho3** [comment]
@7starsea You can directly access the prediction function `predict` which takes in a single row. See the instructions at https://treelite.readthedocs.io/en/latest/tutorials/deploy.html#prediction-instructions
