### ISSUE TITLE
Does the tree lite python API use the Tree lite c API?

### ISSUE THREAD

**Issue by dheerajakula** [dmlc/treelite#276]
Does the tree lite python API use the Tree lite c API? Or are the bindings created directly from cpp, if so how are they created?

**Comment by hcho3** [comment]
Yes, the Python API uses the C API directly. For example: https://github.com/dmlc/treelite/blob/ae5436c45563a5c2ed7aa8f0f41f88fff48f49e4/python/treelite/frontend.py#L450-L451

**Comment by dheerajakula** [comment]
Thanks a lot for the clarification @hcho3
