### ISSUE TITLE
wong of make

### ISSUE THREAD

**Issue by sechenmo** [dmlc/treelite#306]
![wrong](https://user-images.githubusercontent.com/31909538/126443351-9efdaf5c-7f4c-45c7-852b-767dd1003048.PNG)

**Comment by hcho3** [comment]
Make sure that your compiler supports the C++14 standard. For example: GCC 5.0 or later.

**Comment by sechenmo** [comment]
OK.Thanks

> Make sure that your compiler supports the C++14 standard. For example: GCC 5.0 or later.
