### ISSUE TITLE
when I load the so file in C++ the error occurred

### ISSUE THREAD

**Issue by sechenmo** [dmlc/treelite#307]
![ddd](https://user-images.githubusercontent.com/31909538/126614396-251693f0-11f9-4d5c-be68-0298fd7835ac.PNG)

**Comment by hcho3** [comment]
Which OS are you using? And did you install Treelite using pip? The binary `libtreelite_runtime.so` was built using CentOS 7, so you may run into problems if you are using a very old OS.

**Comment by hcho3** [comment]
You may consider building Treelite from the source, by following instructions from https://treelite.readthedocs.io/en/latest/install.html#install-source
