### ISSUE TITLE
Feature request: treelite.Model.from_lightgbm()

### ISSUE THREAD

**Issue by brunofacca** [dmlc/treelite#308]
Thank you for this great library.

Is there a way to load a LightGBM model from a booster object (like `treelite.Model.from_xgboost`, but for LightGBM)? If not, would you consider implementing it? My use case does not require saving the model to a file, but I'm forced to do it to be able to load the model into treelite.

**Comment by hcho3** [comment]
No, currently, Treelite only supports loading LightGBM models from files. I will label this as a feature request.

**Comment by hcho3** [comment]
@brunofacca #332 will add `treelite.Model.from_lightgbm`.
