### ISSUE TITLE
gcc internal error

### ISSUE THREAD

**Issue by marsupialtail** [dmlc/treelite#310]
I am using treelite 2.0.0 from pip.

I use following script:
import treelite, treelite_runtime
def benchmark_treelite():

    model = treelite.Model.load("model","lightgbm")
    model.export_lib(toolchain='gcc', params = {"parallel_comp":4}, libpath='./mymodel.so', verbose=True)
    predictor = treelite_runtime.Predictor('./mymodel.so', verbose=True,nthread=2)
    dmat = treelite_runtime.DMatrix(test_input)
    start = time.time()
    for i in range(1000):
        out_pred = predictor.predict(dmat)
    end = time.time()
    print("== treelite time == ")
    print(end- start)

benchmark_treelite()
~                       
After a while it complains:

File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/treelite/contrib/util.py", line 130, in _create_shared_base
    '{}'.format(result[tid]['stdout']))
treelite.util.TreeliteError: Error occured in worker #0: gcc: internal compiler error: Killed (program cc1)

**It never runs out of memory.** In fact it doesn't come close

**Comment by hcho3** [comment]
It might be related to dmlc/tl2cgen#13. If you are using MacOS, please use GCC from Homebrew.

**Comment by YuPeijia0404** [comment]
May I ask if there is any update on the solution? I met the same problem and I also did not run out of memory. I found the statement "This doesn't cause issue with GCC, but crashes Apple Clang and freezes MSVC" in issue 100, and my toolchain is gcc.
