### ISSUE TITLE
C deployment multithreading.

### ISSUE THREAD

**Issue by marsupialtail** [dmlc/treelite#318]
When you link against the mymodel.so directly, how do you enable multithreading?

**Comment by marsupialtail** [comment]
Do I need to provide more information about this issue? I know how to enable multithreading using the Treelite runtime C API. But how do you enable multithreading when you are linking against the .so file directly?

**Comment by j-proc** [comment]
I think all the APIs use some input when you load the .so. It seems like for the [C API](https://treelite.readthedocs.io/en/latest/treelite-c-api.html#predictor-interface) that would be the `num_worker_thread` parameter.

**Comment by hcho3** [comment]
@marsupialtail If you are not using the Treelite runtime C API, you will need to implement your own parallel loop that calls `predict()` function.
