### ISSUE TITLE
[FEA] Check correct model type for XGBoost.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/treelite#324]
I recently ran into a user error when I feed a JSON model to FIL without specifying `model_type`, which lead to a strange error in `std::string`.  We can prevent this type of error and provide an informative error message by checking the first byte of input.  For JSON model, it should always start with "{".  If the model is edited by the user then it might contain empty space at the beginning before "{", we can either handle it by skipping or simply ask the user to fix it.

**Comment by hcho3** [comment]
Treelite 4.0 will use separate methods for loading legacy and JSON XGBoost models. https://treelite.readthedocs.io/en/v4/treelite-api.html
