### ISSUE TITLE
[GTIL] Remove undefined behavior when negative input is given to a categorical test

### ISSUE THREAD

**Issue by hcho3** [dmlc/treelite#328]
https://github.com/dmlc/treelite/blob/2994be4eb58818de8257aca158699b8792d57937/src/gtil/predict.cc#L52

This line is undefined when `fvalue` has a negative value. Casting a negative `float` into `uint32_t` is undefined.

TODO. Explicitly check whether `fvalue` is negative.

**Comment by levsnv** [comment]
this implementation can cast -0.5f to 0, which may falsely match the first category.

a cast to unsigned directly has been observed to saturate on some processors, while implementing it as if it's a cast to signed int and reinterpreting the bits (a plausible hardware implementation) also rounds -0.5 to 0.
