### ISSUE TITLE
Cannot initialize DMatrix from DataFrame

### ISSUE THREAD

**Issue by ArchitRastogi1** [dmlc/treelite#331]
I am getting errors when I am trying to convert a pandas dataframe which contains string and float. 

**Code** - 

`json = {
    "sepal length": 0.1,
    "sepal width": 0.6,
    "petal length": 1.3,
    "petal width": 1.9,
    "test feat": "a"
}
df = pd.json_normalize(json)
dmat = treelite_runtime.DMatrix(df)
dmat`

**Error** - 
`TypeError: no supported conversion for types: (dtype('O'),)

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-25-b0a991fdb46b> in <module>
      7 }
      8 df = pd.json_normalize(json)
----> 9 dmat = treelite_runtime.DMatrix(df)
     10 dmat

~/anaconda3/envs/python3/lib/python3.6/site-packages/treelite_runtime/predictor.py in __init__(self, data, data_format, dtype, missing, feature_names, feature_types, verbose, nthread)
    292                 self._init_from_csr(csr, dtype=dtype)
    293             except Exception as e:
--> 294                 raise TypeError(f'Cannot initialize DMatrix from {type(data).__name__}') from e
    295         self.feature_names = feature_names
    296         self.feature_types = feature_types

TypeError: Cannot initialize DMatrix from DataFrame`

is is because multiple dtypes are not supported, do we have plan to include multiple dtypes in DMatrix?

**Comment by hcho3** [comment]
Treelite requires all features to be numerical. Make sure to remove all string values from the input matrix.
