### ISSUE TITLE
xgboost model with float64 data 

### ISSUE THREAD

**Issue by yby9212** [dmlc/treelite#363]
hi~

I tried to convert xgboost model into treelite to do inference, but I get different  (about 1e-3) results between

```python
from xgboost import XGBClassifier

model = XGBClassifier()
model.load_model('test.model')

res = model.predict_proba(data)
```

and

```python
import treelite_runtime

model = treelite_runtime.Predictor('test.so')
_dmat = treelite_runtime.DMatrix(data, dtype='float64')
res = model.predict(_dmat)
```

The dtype of my data is float64, but I found  treelite model.threshold_type = 'float32'.

Is that what made the predict results difference？

If so, can I convert xgboost model to treelite with dtype float64?

Thank you ~

**Comment by hcho3** [comment]
@yby9212 XGBoost models are encoded using float32. In addition, the `predict_proba()` method in XGBoost will convert data into float32 before computing the prediction.

>  can I convert xgboost model to treelite with dtype float64?

No, if we were to change the model to float64, we'd deviate even further from XGBoost's behavior. (XGBoost always converts data into float32 first.) To ensure that you get consistent results, please convert your data into float32.
