### ISSUE TITLE
Add support to release Linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [dmlc/treelite#374]
I’m trying to build Linux aarch64 wheels but while building `treelite-build.cpu` image, the following error is arising: 
```
runtime: failed to create new OS thread (have 2 already; errno=22) 
fatal error: newosproc 
```
The error seems to be due to qemu. Since azure pipelines uses qemu to build aarch64 wheels, we can use other CI, such as CircleCI which have aarch64 build agents, to build aarch64 wheels. 

@hcho3, Please let me know your interest in releasing Linux aarch64 wheels. I can help with this.

**Comment by hcho3** [comment]
You can install Treelite using Conda: https://anaconda.org/conda-forge/treelite

**Comment by hcho3** [comment]
I don't think I'd have bandwidth to make aarch64 wheels for PyPI. Conda-forge supports aarch64 out of the box, so that will be our primary way for supporting aarch64
