### ISSUE TITLE
Support XGBoost 1.6

### ISSUE THREAD

**Issue by hcho3** [dmlc/treelite#379]
- [x] Handle the extra slope parameter in the pseudo-Huber loss: #380
- [x] Support UBJSON serialization format
- [x] Support [multi-output regression](https://xgboost.readthedocs.io/en/latest/tutorials/multioutput.html).
- [x] Support multi-class classifiers with `num_parallel_tree > 1`: #383

**Comment by hcho3** [comment]
@trivialfis Anything else we should add to this list?

**Comment by trivialfis** [comment]
The `num_parallel_tree` is now a model parameter.

**Comment by trivialfis** [comment]
I don't think it's necessary to support ubjson in treelite unless the current json loading is not efficient enough.

**Comment by hcho3** [comment]
Got it, I'll postpone UBJSON support for the time being.

**Comment by hcho3** [comment]
~It turns out Treelite doesn't support multi-class classifiers with `num_parallel_tree > 1`.~ Fixed in #383

**Comment by hcho3** [comment]
The current version of Treelite throws a clear error when a multi-target model is given:
```
num_target must be 1; Treelite doesn't support multi-target regressor yet
```

I will create a new version of Treelite now. The remaining TODO items will be tackled in a future version.

**Comment by hcho3** [comment]
Closing. Treelite 4.0 can handle multi-output models just fine.
