### ISSUE TITLE
Support sklearn HistGradientBoosting models

### ISSUE THREAD

**Issue by tczhao** [dmlc/treelite#386]
[HistGradientBoostingRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingRegressor.html#sklearn.ensemble.HistGradientBoostingRegressor)

[HistGradientBoostingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingClassifier.html#sklearn.ensemble.HistGradientBoostingClassifier)

---

I'm very keen to tackle this issue myself. I hope that's ok with you @hcho3

**Comment by hcho3** [comment]
I'm on vacation until July 1. If you're interested in helping out, let's talk when I'm back.
