### ISSUE TITLE
High memory usage and response time for one of Treelite containers

### ISSUE THREAD

**Issue by shubh0508** [dmlc/treelite#392]
I am using a multithreaded FastAPI application with treelite-based inference in python. 
I am using gunicorn to spawn FastAPI uvicorn workers.
My model is XGBReranker and I have converted it to Treelite with a clang toolchain without any extra clang options.
I am observing randomly High memory usage and response time from one of treelite containers for a model.

On checking predict function doc I found following comment:
> Perform batch prediction with a 2D sparse data matrix. Worker threads will internally divide up work for batch prediction. Note that this function may be called by only one thread at a time.

So, I am wondering if FastAPI threads are causing this or TREELITE_BIND_THREADS option. 
I tried to set a single thread on FastAPI but the issue is still persistent. Recompiling the model doesn't solve this either.
Also, does Treelite will have a single runtime regardless of the number of Uvicorn workers or processes I spawn for the prediction?

Attacking grafana observations the model for reference.

<img width="1737" alt="Screenshot 2022-08-10 at 11 26 13 PM" src="https://user-images.githubusercontent.com/19424837/183985131-1d335456-7d27-456e-8e88-e8a49d8f4faf.png">

Current state of deployed container. We can observe that a single container is still having higher CPU usage and memory usage even with 0 throughput. 
<img width="1744" alt="Screenshot 2022-08-10 at 11 39 23 PM" src="https://user-images.githubusercontent.com/19424837/183985866-ec7a4f89-a78c-40eb-a7fc-46243f7327a6.png">

I am using AWS c4.2xlarge instances to deploy these models.

**Comment by hcho3** [comment]
Do you have a big model? How big is it? A few recommendations:
* Set environment variable `TREELITE_BIND_THREADS=0`
* Use `treelite.gtil.predict`, where you don't need to compile the model.
* Use a better maintained inference library such as [Triton Forest Inference Library](https://github.com/triton-inference-server/fil_backend)

**Comment by shubh0508** [comment]
@hcho3 Thanks for replying so promptly. I am grateful to have had a conversation with the lead XGBoost maintainer. Looking forward to contributing to projects with so wide impacts. 

To our first question, The model is not that big. I am using Treelite in another XGBRegressor model deployment where the model size is 700MB and 5000 to 8000 trees. That model is working perfectly and it is providing us with 10X improvements in the inference process.

This model has 29 features, 288 trees, and a 100MB file size(`.model` format).
`
<bound method XGBModel.get_xgb_params of XGBRanker(base_score=0.5, booster='gbtree', colsample_bylevel=1,
          colsample_bynode=0.9, colsample_bytree=1, gamma=1.5, gpu_id=-1,
          grow_policy='lossguide', importance_type='gain',
          interaction_constraints='', learning_rate=0.1, max_bin=1024,
          max_delta_step=0, max_depth=0, max_leaves=4096, min_child_weight=1,
          missing=nan, monotone_constraints='()', n_estimators=500, n_jobs=10,
          num_parallel_tree=1, objective='rank:pairwise', random_state=0,
          reg_alpha=10, reg_lambda=1, scale_pos_weight=None, subsample=1,
          tree_method='hist', use_label_encoder=False, validate_parameters=1, ...)>
`


1. I have set TREELITE_BIND_THREADS=0 and it seems to have resolved the issue. Will observe it for a few days and update here if everything's alright.

2. Using `treelite.gtil.predict` is showing higher latencies as compared to compiled model(450us vs 20us), and I want to deploy the model on the production servers. So, `treelite_runtime.Predictor().predict` seems best for it. Maybe I am missing something in `treelite.gtil.predict`?

3. Thanks for suggesting the Triton library. It seems promising. Will check it out and see if it works for our usecase.

4. I have one more question regarding CLang options. Using `-ffast-math` option is showing me significant upside. 
With `-static -ffast-math` option, I am able to compile the model but then at runtime, creating the `treelite_runtime.Predictor` object raises an error that `model.so` is not in the right format or something.
Also, when I use other options like  `-Ofast` and `-emit-llvm`, I am unable to compile the model with Treelite. I am getting `predictor.so` not found error. Can you suggest some ways to use them?

**Comment by hcho3** [comment]
> I have set TREELITE_BIND_THREADS=0 and it seems to have resolved the issue.

Great!

As for the `-ffast-math` option, I have not used it so I cannot help you much here.

**Comment by shubh0508** [comment]
Setting `TREELITE_BIND_THREADS=0` has resolved the issue, so closing this issue.

> I have used `-ffast-math` option in many models and it is showing 10-15% improvement in the interfernce.
