### ISSUE TITLE
[Feature request/Question] Support building DMatrix from plain Python list

### ISSUE THREAD

**Issue by thvasilo** [dmlc/treelite#393]
Currently `treelite_runtime.DMatrix` takes as input one of a:
* Filepath
* Numpy NDArray
* Scipy CSR Matrix
* Pandas Dataframe

For data that comes into a different format during prediction (e.g. a list of floats) do we need to convert to one of these types before conversion? Or is it possible to pass in a `List[float` to the DMatrix constructor?

If that's not possible I would like to put this in as feature request (and I can probably work on it depending on the complexity) s.t. when we do Python-based prediction we don't have to pull in a heavy dependency like Numpy/Scipy/Pandas and are instead able to use plain Python objects.

**Comment by hcho3** [comment]
I marked it as a feature request.

**Comment by thvasilo** [comment]
I actually tested this today and it seems like the [fallback](https://github.com/dmlc/treelite/blob/mainline/runtime/python/treelite_runtime/predictor.py#L300) in the DMatrix init works for my usecase (list of floats). Closing.
