### ISSUE TITLE
Feature request: add support for RandomForestRegressor with multiple outputs

### ISSUE THREAD

**Issue by ageron** [dmlc/treelite#414]
Unless I'm mistaken, it looks like there's support for multiclass classification, but not for multioutput regression. Is this on the roadmap? If so, I'm happy to help.

**Comment by hcho3** [comment]
@ageron It's part of #379, although we don't yet have a concrete timeline for implementing the support.

**Comment by ageron** [comment]
Thanks for your answer. 👍  I guess this is a duplicate issue then, sorry for the noise. Closing.
