### ISSUE TITLE
Deploy with uwsgi

### ISSUE THREAD

**Issue by idiomer** [dmlc/treelite#42]
I'm using treelite to deploy with my xgboost model. For higher QPS, I must parallelize my program. So, I use uwsgi to complete it.  

However, it seems to not work. And "Time per request"  is linear growth  with "request concurrent".  Could you give me some advisement. 

Below is my "apache ab" report:

1. request with **1** concurrent (ab -c 1 -n 1000 -p postfile.txt http://localhost:6181/api)
``` shell 
Concurrency Level:      1
Time taken for tests:   5.163 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      92000 bytes
Total body sent:        232000
HTML transferred:       21000 bytes
Requests per second:    193.68 [#/sec] (mean)
Time per request:       5.163 [ms] (mean)
Time per request:       5.163 [ms] (mean, across all concurrent requests)
Transfer rate:          17.40 [Kbytes/sec] received
                        43.88 kb/s sent
                        61.28 kb/s total
```

2. request with **10** concurrent (ab -c 10 -n 1000 -p postfile.txt http://localhost:6181/api)
``` shell 
Concurrency Level:      10
Time taken for tests:   3.453 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      92000 bytes
Total body sent:        232000
HTML transferred:       21000 bytes
Requests per second:    289.59 [#/sec] (mean)
Time per request:       34.532 [ms] (mean)
Time per request:       3.453 [ms] (mean, across all concurrent requests)
Transfer rate:          26.02 [Kbytes/sec] received
                        65.61 kb/s sent
                        91.63 kb/s total
```

**Comment by hcho3** [comment]
Are you using `predict()` or `predict_instance()`?

**Comment by idiomer** [comment]
I  use the `predict()` method

**Comment by idiomer** [comment]
No matter how many workers I use,  the CPU usage is always on 6% (100/16, the machine has 16 cores)

**Comment by hcho3** [comment]
Since you have multiple concurrent requests, you should install the latest master and use `predict_instance()`.

**Comment by idiomer** [comment]
Is it said that the predict method can not be deployed with multiprocess？ And is there any documents to explain the reasons?
 Because one request in my application needs to predict multiple instances(8-24), I think that using predict method to predict them is a more elegant solution.

**Comment by hcho3** [comment]
How many threads are calling `predict()` simultaneously? The `predict()` method is not designed to be called by multiple threads. This is because `predict()` method performs **batch prediction**, where each request has a large batch of instances (100, 1000, or more) and the group of worker threads operate on one request at a time. That means that you cannot have more than one request performed using `predict()`. The Java API doc does mention this fact (see [here](https://treelite.readthedocs.io/en/latest/javadoc/ml/dmlc/treelite4j/Predictor.html#ml.dmlc.treelite4j.Predictor.predict%28SparseBatch,%20boolean,%20boolean%29)) but the Python API doc does not. Sorry about the confusion, and let me update the Python API doc.

Note that `predict_instance()` can be called by multiple threads, and with `predict_instance()` multiple requests can be run simultaneously.

> Because one request in my application needs to predict multiple instances(8-24), I think that using predict method to predict them is a more elegant solution.

The number of instances is not high enough to warrant batch prediction. You should use `predict_instance()`.

**Comment by hcho3** [comment]
I updated the documentation: https://treelite.readthedocs.io/en/latest/treelite-runtime-api.html#treelite.runtime.Predictor.predict

**Comment by idiomer** [comment]
I try the `predict_instance` method, but it is slower than `original xgboost.predict` to predict one instance (it took 65ms but `original xgboost.predict` only took 20ms). Is there any better way to perform higher concurrent and qps?

**Comment by hcho3** [comment]
@idiomer Does it scale with respect to number of threads?

**Comment by hcho3** [comment]
Also, you can try creating a batch from multiple incoming requests

**Comment by idiomer** [comment]
@hcho3  `predict_instance` performs as `predict` method. I use uwsgi to open 8 precess(workers) to serve, and use apache ab with multiple threads(1, 8, 30) to request my server. But 8 workers only use 100%(=12.5%*8) CPU, not 800% CPU.
Below is the screenshot of top command: 
![image](https://user-images.githubusercontent.com/17400651/45138985-e0605380-b1e0-11e8-915d-8b0f0b4fc28f.png)

**Comment by hcho3** [comment]
I wonder if we are running into limitations of Python. Does uwsgi support other language bindings, like C or Java?

**Comment by hcho3** [comment]
I would like to work with you closely to improve performance for concurrent requests

**Comment by hcho3** [comment]
Also, can you.post a dummy sata example that I can run on my end? I'd like to learn more about use cases like yours and make taegeted improvements.

**Comment by idiomer** [comment]
> I wonder if we are running into limitations of Python. Does uwsgi support other language bindings, like C or Java?

-------
Just now, I try to run my application with multiple ports without uwsgi.  It works! I can use `predict` method to process the concurrent requests.
So, I think that uwsgi doesn't  support other language bindings. 
Thank you very much for your advice and patience.

**Comment by hcho3** [comment]
That's great to hear. Let me know if you have other questions.
