### ISSUE TITLE
Missing predictor.h

### ISSUE THREAD

**Issue by lv-zhaoyu** [dmlc/treelite#44]
The version 0.32  has no predictor.h?

**Comment by hcho3** [comment]
Here it is: https://github.com/dmlc/treelite/blob/master/runtime/native/include/treelite/predictor.h

**Comment by lv-zhaoyu** [comment]
Sorry，may I ask  how can  I get the library object file(.so) containing my lightgbm model code by using C++? I can't find the code in treelite.

**Comment by hcho3** [comment]
To generate *.so file, we recommend that you use the Python package, since it automates the compilation step (where GCC or Clang is invoked). Otherwise, you'll have to invoke GCC/Clang manually.
