### ISSUE TITLE
Add directory exist check in _load_lib for add_dll_directory

### ISSUE THREAD

**Issue by pagoenka** [dmlc/treelite#521]
Getting error on Windows machine with Python 3.9 like below

`FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python39\\Library\\bin'`

In core.py, its checking for python greater than equals to 3.8 & windows platform, whereas this directory doesn't exist in venv, when I added empty directory in venv as below, it worked.

> venv/Library/bin

https://github.com/dmlc/treelite/blob/1c3340741d3b5e5763b4b1a74a589c96d7f7c5d6/python/treelite/core.py#L19

**Comment by hcho3** [comment]
Fixed in `v4` branch. https://github.com/dmlc/treelite/blob/281503a50fa80ca04ba769351c913dde10772577/python/treelite/libpath.py#L31-L52
