### ISSUE TITLE
xgboost json model fails to load 

### ISSUE THREAD

**Issue by LLautenbacher** [dmlc/treelite#561]
Hi,

I have a xgboost model in JSON format when I try to load it with treelite version >4.0 (`treelite.frontend.load_xgboost_model`) I get the error `Node with key 1 is orphaned -- it cannot be reached from the root node`. With version 3.9 (`treelite.Model.load`) it worked without issue.  Do you have an idea what is causing this, or how I can convert the json into a format that works with treelite >4.0? 

You can download the model file from Zenodo: https://zenodo.org/records/7576604

Thank you for your help in advance!

**Comment by hcho3** [comment]
Can you also share the script you used for training the XGBoost model? I'd like to know the list of hyperparameters.

**Comment by LLautenbacher** [comment]
I didn't train the model myself. But this is probably the [script](https://github.com/compomics/ms2pip/blob/releases/train_scripts/train_xgboost_c.py) that was used to train it and this should be the hyperparameters selected during tuning.
![image](https://github.com/dmlc/treelite/assets/59884643/92e281a4-688f-4497-b066-c44663e181d7)
Taken from the supplement of this [paper](https://academic.oup.com/nar/article/51/W1/W338/7151340#supplementary-data).

**Comment by hcho3** [comment]
@LLautenbacher The bug should be fixed in the upcoming Treelite release. Thanks!
