### ISSUE TITLE
Typo in the editing models tutorial

### ISSUE THREAD

**Issue by stephenpardy** [dmlc/treelite#575]
I am very excited to explore `treelite` more, thank you for the nice package. 

While experimenting with editing models I noticed that the tutorial is missing a line. I have a fix in a fork if you are willing to accept PRs:
https://github.com/stephenpardy/treelite/commit/4b203add20f124f8bc594bb29c82a5f735aace4d

**Comment by hcho3** [comment]
Yes, please submit a pull request.

**Comment by stephenpardy** [comment]
PR opened here: https://github.com/dmlc/treelite/pull/576
