### ISSUE TITLE
Treelite release cadence and possibiliy for patch releases

### ISSUE THREAD

**Issue by daria-shaw** [dmlc/treelite#592]
What's the release cadence for treelite?

There's a [dll loading fix](https://github.com/dmlc/treelite/commit/469fc78e62d257ca7716e9c1a08c4ae0575b2178) that solves a bug for installing treelite on windows with pyenv which is not available in the latest release (4.3.0).

Depending on how you handle releases, would it be possible for a 4.3.x patch?

**Comment by hcho3** [comment]
I will work on a next minor release (4.4.0) by next week.

**Comment by hcho3** [comment]
I just released the 4.4.1 release.
