### ISSUE TITLE
How to use this library in Android or IOS platform？

### ISSUE THREAD

**Issue by lyq123180** [dmlc/treelite#6]
I want to use Treelite for inference in Android and IOS platform.
1.Is this library compatible with xgboost model file?
Because I plan to train the model using xgboost，and inference using the treelite.
2.Is there any dependence on linux-only library?
I was try to compile the xgboost with Android NDK,however I find there are many dependence on linux-only library,for example the execinfo.h.I can't find such file in Android NDK.

**Comment by lyq123180** [comment]
I notice there is a funcion for model loading in C-API.
`int TreeliteLoadXGBoostModel(const char* filename,ModelHandle* out) {`
still,I want to know if there is any example for C-API.

**Comment by lyq123180** [comment]
I try to compile the library with Android NDK but encounter the same problem with the xgboost.
For the dmlc library need  'asm/types.h'，but I can't find this file in Android NDK.
`[  3%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.oclang++: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]In file included from /home/panmin/下载/treelite/dmlc-core/src/config.cc:4:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/sstream:38:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/istream:38:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/ios:38:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/iosfwd:40:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/postypes.h:40:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:44:In file included from /home/panmin/Android/android-ndk-r15b/sysroot/usr/include/wchar.h:32:In file included from /home/panmin/Android/android-ndk-r15b/sysroot/usr/include/stdio.h:42:In file included from /home/panmin/Android/android-ndk-r15b/sysroot/usr/include/sys/types.h:36:/home/panmin/Android/android-ndk-r15b/sysroot/usr/include/linux/types.h:21:10: fatal error:       'asm/types.h' file not found#include <asm/types.h>         ^~~~~~~~~~~~~1 error generated.dmlc-core/CMakeFiles/dmlc.dir/build.make:62: recipe for target 'dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.o' failed`

**Comment by hcho3** [comment]
@lyq123180 As for now, treelite is in alpha stage; we are currently focusing on support for Windows, Mac OS X, and Linux. We may consider adding support on mobile in the future.

Answer to your questions:
1. Yes, treelite is designed to interface with XGBoost.
2. I am not sure whether anyone has tested compiling dmlc-core on Android. There is one reference to Android here: https://github.com/dmlc/dmlc-core/blob/master/make/dmlc.mk

**Comment by hcho3** [comment]
As for C API, we haven't gotten around writing a documentation yet. For now, you can read the comment in c_api.h and c_api_runtime.h.

**Comment by hcho3** [comment]
@lyq123180 Actually, **you do not have to compile treelite on Android**! It's best to think of treelite as a **compiler**, which will convert your tree model into a C program. So do the following:
1. Compile treelite on a laptop or desktop.
2. Use treelite to produce a C program.
3. Compile the produced C program on Android.

**Comment by hcho3** [comment]
@lyq123180 We do plan to write a tutorial on how to deploy tree models on Android and iOS. We'll try to get this done within 2-3 weeks.

**Comment by Vitorbnc** [comment]
Is deploying to Android currently possible with the new 0.3 release?

**Comment by fdchiu** [comment]
If you need someone to do the android deployment and porting, I might be able to help.

**Comment by yukezhang** [comment]
> @lyq123180 We do plan to write a tutorial on how to deploy tree models on Android and iOS. We'll try to get this done within 2-3 weeks. Unfortunately, we'll be delaying the tutorial until a future release of treelite. Thanks for your understanding.

Can we get a tutorial on how to deploy tree models on Android and iOS now?

**Comment by yukezhang** [comment]
> I try to compile the library with Android NDK but encounter the same problem with the xgboost.
> For the dmlc library need 'asm/types.h'，but I can't find this file in Android NDK.
> `[ 3%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.oclang++: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]In file included from /home/panmin/下载/treelite/dmlc-core/src/config.cc:4:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/sstream:38:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/istream:38:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/ios:38:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/iosfwd:40:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/postypes.h:40:In file included from /home/panmin/Android/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:44:In file included from /home/panmin/Android/android-ndk-r15b/sysroot/usr/include/wchar.h:32:In file included from /home/panmin/Android/android-ndk-r15b/sysroot/usr/include/stdio.h:42:In file included from /home/panmin/Android/android-ndk-r15b/sysroot/usr/include/sys/types.h:36:/home/panmin/Android/android-ndk-r15b/sysroot/usr/include/linux/types.h:21:10: fatal error: 'asm/types.h' file not found#include <asm/types.h> ^~~~~~~~~~~~~ 1 error generated.dmlc-core/CMakeFiles/dmlc.dir/build.make:62: recipe for target 'dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.o' failed`

I have the same problem building xgboost with NDK, did you resolve this problem?

**Comment by victor1993tju** [comment]
Can we get a tutorial on how to deploy tree models on Android and iOS now?

**Comment by liuyibox** [comment]
Do we have a tutorial or enhancements already on deploying tree models on Android now?
