### ISSUE TITLE
pip3 install --user treelite not working

### ISSUE THREAD

**Issue by aishgrt1** [dmlc/treelite#60]

**Comment by aishgrt1** [comment]
It says : 

Could not find a version that satisfies the requirement treelite. No matching distribution found for treelite.

**Comment by hcho3** [comment]
Which Python version are you using?

**Comment by aishgrt1** [comment]
Python 3

**Comment by hcho3** [comment]
https://pypi.org/project/treelite has wheels for Python 3.6. Are you using an OS that's not Windows, Mac OSX, or Linux?

**Comment by hcho3** [comment]
From the documentation:

> This method is available for only Windows, Mac OS X, and Linux. For other operating systems, see the next section.

**Comment by aishgrt1** [comment]
I don't understand what to do for other systems

**Comment by aishgrt1** [comment]
@hcho3  Hey can  you help me install it for other operating systems ?

**Comment by hcho3** [comment]
You should compile from source. The documentation has steps for compiling.
