### ISSUE TITLE
support for QuickScorer and RapidScorer

### ISSUE THREAD

**Issue by guolinke** [dmlc/treelite#67]
any future supports for the state-of-the-art research like 
QuickScorer (https://www.cse.cuhk.edu.hk/irwin.king/_media/presentations/sigir15bestpaper.pdf)
and RapidScorer (https://www.kdd.org/kdd2018/accepted-papers/view/rapidscorer-fast-tree-ensemble-evaluation-by-maximizing-compactness-in-data) ?

**Comment by superbobry** [comment]
FYI QuickScorer has a [patent pending](https://patents.google.com/patent/WO2016203501A1/en), this makes it incompatible with the project license.

**Comment by hcho3** [comment]
Indeed QuickScorer has a patent attached to it. I’ll look at RapidScorer when I have a chance.

**Comment by superbobry** [comment]
AFAIU the patent is not yet granted, and might not even be granted in the end, there is just a patent application at the moment. Regardless, this is potentially problematic for an open-source library.

**Comment by hcho3** [comment]
@guolinke @superbobry I may consider adding RapidScorer support to Treelite in the near future.

**Comment by superbobry** [comment]
Bear in mind that RapidScore is a variant of QuickScorer and could potentially fall under the IP covered by the pending patent.

**Comment by hcho3** [comment]
@superbobry I will seek legal counsel from my org.

**Comment by trivialfis** [comment]
Seems interesting.  Maybe we can try plain old
` i = (i << 1) + 1 + int(node.threshold < value)`
with fully balanced trees for branch removal first, then move to more complex algorithms.   My interest is in GPU support so starting simple might be better.
