### ISSUE TITLE
static lib and BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by headupinclouds** [dmlc/treelite#9]
Great project!  This really simplifies deployment.

Would you consider omitting the forced `SHARED` library build and deferring to CMake's [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html#build-shared-libs) so that the user can choose?  I'm happy to send a PR.

https://github.com/dmlc/treelite/blob/5e057bf4d7a42d6c28024f746f9b78babf17eca4/CMakeLists.txt#L118-L119

```
add_library(treelite SHARED $<TARGET_OBJECTS:objtreelite> $<TARGET_OBJECTS:objtreelite_common>)
add_library(treelite_runtime SHARED $<TARGET_OBJECTS:objtreelite_runtime> $<TARGET_OBJECTS:objtreelite_common>)
```

**Comment by hcho3** [comment]
Thanks for your suggestion. Can you think of any scenario where building a static library would be useful? Right now, the treelite library is `SHARED` so that the Python package can access it using `ctypes.cdll.LoadLibrary`.

**Comment by headupinclouds** [comment]
> Can you think of any scenario where building a static library would be useful?

I'm thinking primarily about direct integration in C/C++ applications or SDK's, where a project will often link against several (or many) different static libraries: opencv, boost, png, zlib, treelite, etc.  In such cases, it is often more convenient to work with static libs if you want to end up with a single application (or shared lib).  This is the default for most C/C++ libraries.

**Comment by hcho3** [comment]
With the latest commit, you should be able to build static libraries. Simply run
```console
cmake .. -DBUILD_SHARED_LIBS=OFF
```

**Comment by headupinclouds** [comment]
Thanks.

**Comment by hcho3** [comment]
And thanks for your feedback!
