### ISSUE TITLE
Error while using on OSX

### ISSUE THREAD

**Issue by navsaini** [dmlc/treelite#90]
After I `import treelite` using python 3.6, I get the following error message.

```
OSError: dlopen(/usr/local/lib/python3.6/site-packages/treelite/libtreelite.dylib, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /usr/local/lib/python3.6/site-packages/treelite/libtreelite.dylib
  Reason: image not found
```

I tried both installing using pip and compiling manually. Is there something I'm missing?

**Comment by navsaini** [comment]
python was still linked to the pip install instead of the manual compile

**Comment by yukezhang** [comment]
> OSError

I have the same problem after pip install treelite import treelite,get the following message:

OSError: dlopen(/usr/local/lib/python3.6/site-packages/treelite/libtreelite.dylib, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /usr/local/lib/python3.6/site-packages/treelite/libtreelite.dylib
  Reason: image not found

**Comment by hcho3** [comment]
@yukezhang We do not provide Python wheels for Mac OSX. Please compile from the source, by following https://treelite.readthedocs.io/en/latest/install.html#compile-treelite-from-the-source
