### ISSUE TITLE
Question about calling"int TreelitePredictorPredictInst(...)" from C++ codebase

### ISSUE THREAD

**Issue by MeBlueDolphin** [dmlc/treelite#93]
Hi,

  First off, much kudos to you for providing this valuable tool! I have perhaps a naive question.  I am using treelite to speedup xbgoost's inference where I need to do prediction on data samples one row at a time in a C++ codebase.  I see that you provide an interface for TreelitePredictorPredictInst() in treelite/runtime/native/include/treelite/c_api_runtime.h, but I do not see this method in the compiled shared object library libtreelite.so.  Is it possible to provide a c_api_runtime example on how to call it?

Best regards,
Ismail

**Comment by hcho3** [comment]
Can you compile from the source? The binary package is outdated. I've been busy and haven't gotten a chance to update the binary.

**Comment by MeBlueDolphin** [comment]
Thank you for your quick reply.  I did compile the source code to generate and generated the shared object library in treelight/lib/libtreelite.so.   However, when I grep the contents for **_PredictInst_**, I only see the following:

/home/libs/treelite/lib$ nm -D libtreelite.so | egrep PredictInst 
000000000033c850 u _ZGVZN4dmlc2io15LocalFileSystem11GetInstanceEvE8instance
00000000000ea9b0 T _ZN4dmlc2io10FileSystem11GetInstanceERKNS0_3URIE
000000000033c840 u _ZZN4dmlc2io15LocalFileSystem11GetInstanceEvE8instance

  Do I need to build another shared object that contains the runtime API's?

Greatly appreciated,
Ismail

**Comment by hcho3** [comment]
Look for libtreelite_runtime.so

**Comment by MeBlueDolphin** [comment]
Thank you found it under treelite/runtime/native/lib.
So, I simply need to (1) include "c_api_runtime.h" in my code and (2) link libtreelite_runtime.so and should be good to go, right?

**Comment by hcho3** [comment]
Yes

**Comment by MeBlueDolphin** [comment]
Thank you!
Very much appreciated

**Comment by hcho3** [comment]
No problem. Thanks for using Treelite!
