### ISSUE TITLE
Option for 64bit input data

### ISSUE THREAD

**Issue by jbagaipo** [dmlc/treelite#95]
Issue #55 updated the model translation to use double precision for the thresholds and leaf values, however, the input data is still using 32bit numpy arrays / floats. This leads to incorrect predictions in models that use double precision data.

**Comment by hcho3** [comment]
Indeed, LightGBM uses 64-bit floating-point numbers. The right way is to support multiple types. I'm planning to work on it this month. Stay tuned.

**Comment by hcho3** [comment]
The recent refactor (#196, #198, #199, #201, #203) added an option to use float64 data type.
